In [1]:
import numpy as np 

In [2]:
l = [1,2,3,6,5,4,8,7,9]
arr = np.array(l)
print(arr)

[1 2 3 6 5 4 8 7 9]


In [3]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [4]:
l2 = [[[1,2,3,],[4,5,6,],[7,8,9],[10,11,12]]]

In [5]:
l2

[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]]

In [6]:
np.shape(l2)

(1, 4, 3)

In [7]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [8]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [9]:
arr.shape

(9,)

In [10]:
l2 = np.reshape(l2,(3,2,2))

In [11]:
np.shape(l2)

(3, 2, 2)

In [12]:
print(l2)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [13]:
l2 [0,1,0]

np.int64(3)

In [14]:
l2 [0,0,0]

np.int64(1)

In [15]:
l2 [2,1,:]

array([11, 12])

In [16]:
l5 = [1,2,3,4,5,6,7,8,9,10]

In [17]:
l5

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [18]:
l5 * 2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [19]:
l5 = np.array(l5)

In [20]:
l5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
l5.shape

(10,)

In [22]:
l5 = l5.reshape(5,2)

In [23]:
l5

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [24]:
l6 = [1,2,3,4,5,6,7,8,9,10]

In [25]:
arr=np.array(l6)

In [26]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr* 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [28]:
arr + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [29]:
arr - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [30]:
arr.shape


(10,)

In [31]:
arr = arr.reshape(2,5)

In [32]:
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [33]:
l7 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [34]:
l7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [35]:
l7.shape

(12,)

In [36]:
l8 = np.array([1,8,4,5,6,9,7,1,2,20,11,13])

In [37]:
l8

array([ 1,  8,  4,  5,  6,  9,  7,  1,  2, 20, 11, 13])

In [38]:
l8.shape

(12,)

In [39]:
l8 = l8.reshape(1,12)

In [40]:
l8.shape

(1, 12)

In [41]:
l9 = l8 + l7

In [42]:
l9 

array([[ 2, 10,  7,  9, 11, 15, 14,  9, 11, 30, 22, 25]])

In [43]:
l9.shape

(1, 12)

In [44]:
l10 = np.array([1,5,8,7,4,6,9,2,3,6,5,4,7,8])

In [45]:
l10

array([1, 5, 8, 7, 4, 6, 9, 2, 3, 6, 5, 4, 7, 8])

In [46]:
l10.shape

(14,)

In [47]:
l10 = l10.reshape(14,1)

In [48]:
l11 = l10 + l7

In [49]:
l11

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [50]:
l12 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24])

In [51]:
l12 = l12.reshape(2,12)

In [52]:
l13 = l12 + l7

In [53]:
l13.shape

(2, 12)

In [54]:
l12 = l12.reshape(2,12)

In [55]:
l13 = l7 + l12

to add two matrix(array) we have to make their y-axis or columns of same value.

In [56]:
l13

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24],
       [14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36]])

In [57]:
l7.shape

(12,)

In [58]:
l12.shape

(2, 12)

In [59]:
l9.shape

(1, 12)

In [60]:
arr1=l9+l12

In [61]:
arr1

array([[ 3, 12, 10, 13, 16, 21, 21, 17, 20, 40, 33, 37],
       [15, 24, 22, 25, 28, 33, 33, 29, 32, 52, 45, 49]])

In [62]:
arr3=l9.reshape(1,12)

In [63]:
arr3

array([[ 2, 10,  7,  9, 11, 15, 14,  9, 11, 30, 22, 25]])

In [64]:
arr3.shape


(1, 12)

In [65]:
arr2 = l9+l7

In [66]:
arr2

array([[ 3, 12, 10, 13, 16, 21, 21, 17, 20, 40, 33, 37]])

In [67]:
l7.shape

(12,)

In [68]:
arr4=l7+l9

In [69]:
arr4

array([[ 3, 12, 10, 13, 16, 21, 21, 17, 20, 40, 33, 37]])

In [70]:
arr5 = arr4+arr3

In [71]:
arr5

array([[ 5, 22, 17, 22, 27, 36, 35, 26, 31, 70, 55, 62]])

In [72]:
arr6=l9.reshape(2,6)

In [73]:
arr7=l7.reshape(2,6)

In [74]:
arr8=arr6+arr7

In [75]:
arr8

array([[ 3, 12, 10, 13, 16, 21],
       [21, 17, 20, 40, 33, 37]])

zeros = it is used to make an array of values = 0

In [76]:
arr9 = np.zeros((2,10))

In [77]:
arr9

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [78]:
arr9=np.zeros((5,10),dtype=int)


In [79]:
arr9

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

ones = it is used to generate an array of ony unit digits .

In [80]:
arr = np.ones((9,15))

In [81]:
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

empty = it is used to get an array of randomly generated values or garbage values .

In [82]:
arr = np.empty((4,6))

In [83]:
arr

array([[4.7008511e-315, 0.0000000e+000, 3.4584595e-323, 4.4465908e-323,
        5.4347221e-323, 7.4109847e-323],
       [6.9169190e-323, 4.4465908e-323, 5.4347221e-323, 1.4821969e-322,
        1.0869444e-322, 1.2351641e-322],
       [9.8813129e-324, 4.9406565e-323, 3.4584595e-323, 4.4465908e-323,
        5.4347221e-323, 7.4109847e-323],
       [6.9169190e-323, 4.4465908e-323, 5.4347221e-323, 1.4821969e-322,
        1.0869444e-322, 1.2351641e-322]])

In [84]:
arr = np.empty((4,6),dtype=int)

In [85]:
arr 

array([[951462855,         0,         7,         9,        11,        15],
       [       14,         9,        11,        30,        22,        25],
       [        2,        10,         7,         9,        11,        15],
       [       14,         9,        11,        30,        22,        25]])

arange = it is used to get an array of desired staring point & ending point with how much differnce we want in the two values .

In [86]:
arr = np.arange(0,20,2.5,dtype=np.float64)

In [87]:
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5])

linspace = it is used to make an array of desired staring point & ending point with how much values we want then the funtion will generate the gap itself according to the values 

In [88]:
arr = np.linspace(0,10,20)

In [89]:
arr

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [90]:
arr = np.random.binomial(n=6,p=0.6,size=(2,5))

In [91]:
arr

array([[1, 4, 3, 4, 3],
       [4, 3, 3, 5, 4]])

In [92]:
arr = np.random.binomial(n=1,p=0.5,size=(2,5))

In [93]:
arr

array([[1, 1, 1, 0, 1],
       [0, 1, 1, 0, 1]])

In [94]:
arr = np.random.multivariate_normal(mean=[1,1,1,1],cov=[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]],size=10)

In [95]:
arr

array([[ 0.31584761,  2.8268778 ,  0.0851966 ,  1.9848079 ],
       [-1.04048613,  0.12572462,  1.65370284,  2.63837007],
       [ 1.42652705,  2.45495337,  0.06361625,  0.47918386],
       [ 1.74844037,  0.77605875,  1.48261981, -0.44676553],
       [ 0.16121884,  0.70495136,  0.52035474, -0.81110826],
       [ 0.02224571,  1.5912649 ,  1.07859877,  0.69596925],
       [ 0.14985859, -0.68629435,  2.11324592,  2.01999849],
       [ 0.66560484,  1.42955237,  0.34614788,  0.98539044],
       [ 0.75912096,  2.0148051 ,  2.21657129,  0.50150052],
       [-0.1006651 , -0.33734057, -0.75995738,  0.38425435]])

In [96]:
arr = np.random.multivariate_normal(mean=[1,2,3,4],cov=[[1,0,0,0],[0,2,0,0],[0,0,3,0],[0,0,0,4]],size=10)

In [97]:
arr

array([[ 2.14397143,  3.26788938,  3.35619434,  2.73898254],
       [-0.11729847,  0.86569345,  2.90234425,  3.6363133 ],
       [-0.60724765,  3.07486548,  3.16579842,  3.74870526],
       [ 2.32431516, -0.81549867,  2.46062406,  5.10612288],
       [ 1.53356003,  1.7451646 ,  3.25195482,  2.69891209],
       [ 1.66429574,  2.19050477,  2.14652671,  4.33274462],
       [-0.00905679,  3.473811  ,  2.51045972,  1.00854462],
       [ 2.32005756,  1.91554771,  3.70726656,  3.59785766],
       [ 0.37068377,  1.52658856,  2.80831744,  6.31775824],
       [ 1.94302948,  1.37066888,  5.68390264,  4.81453077]])

In [98]:
arr = np.random.normal(loc=5,scale=1,size=(2,10))

In [99]:
arr

array([[5.67414693, 3.53556952, 6.25225681, 6.46313368, 7.63099855,
        5.68686819, 6.36281377, 4.81913291, 1.85189132, 5.81149668],
       [5.17710988, 6.38680919, 5.7047348 , 5.86838984, 6.15623808,
        5.11462321, 5.06813375, 4.96624779, 4.57339552, 6.11870476]])

In [100]:
arr_mean=np.mean(arr)

In [101]:
arr_mean

np.float64(5.461134759068026)