In [2]:
import numpy as np 

In [3]:
l = [1,2,3,6,5,4,8,7,9]
arr = np.array(l)
print(arr)

[1 2 3 6 5 4 8 7 9]


In [4]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [5]:
l2 = [[[1,2,3,],[4,5,6,],[7,8,9],[10,11,12]]]

In [6]:
l2

[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]]

In [7]:
np.shape(l2)

(1, 4, 3)

In [8]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [9]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [10]:
arr.shape

(9,)

In [11]:
l2 = np.reshape(l2,(3,2,2))

In [12]:
np.shape(l2)

(3, 2, 2)

In [13]:
print(l2)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [14]:
l2 [0,1,0]

np.int64(3)

In [15]:
l2 [0,0,0]

np.int64(1)

In [16]:
l2 [2,1,:]

array([11, 12])

In [17]:
l5 = [1,2,3,4,5,6,7,8,9,10]

In [18]:
l5

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [19]:
l5 * 2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [20]:
l5 = np.array(l5)

In [21]:
l5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
l5.shape

(10,)

In [23]:
l5 = l5.reshape(5,2)

In [24]:
l5

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [25]:
l6 = [1,2,3,4,5,6,7,8,9,10]

In [26]:
arr=np.array(l6)

In [27]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr* 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [29]:
arr + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [30]:
arr - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [31]:
arr.shape


(10,)

In [32]:
arr = arr.reshape(2,5)

In [33]:
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [34]:
l7 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [35]:
l7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
l7.shape

(12,)

In [37]:
l8 = np.array([1,8,4,5,6,9,7,1,2,20,11,13])

In [38]:
l8

array([ 1,  8,  4,  5,  6,  9,  7,  1,  2, 20, 11, 13])

In [39]:
l8.shape

(12,)

In [40]:
l8 = l8.reshape(1,12)

In [41]:
l8.shape

(1, 12)

In [42]:
l9 = l8 + l7

In [43]:
l9 

array([[ 2, 10,  7,  9, 11, 15, 14,  9, 11, 30, 22, 25]])

In [44]:
l9.shape

(1, 12)

In [45]:
l10 = np.array([1,5,8,7,4,6,9,2,3,6,5,4,7,8])

In [46]:
l10

array([1, 5, 8, 7, 4, 6, 9, 2, 3, 6, 5, 4, 7, 8])

In [47]:
l10.shape

(14,)

In [48]:
l10 = l10.reshape(14,1)

In [49]:
l11 = l10 + l7

In [50]:
l11

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [51]:
l12 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24])

In [52]:
l12 = l12.reshape(2,12)

In [53]:
l13 = l12 + l7

In [54]:
l13.shape

(2, 12)

In [55]:
l12 = l12.reshape(2,12)

In [56]:
l13 = l7 + l12

to add two matrix(array) we have to make their y-axis or columns of same value.

In [57]:
l13

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24],
       [14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36]])

In [58]:
l7.shape

(12,)

In [59]:
l12.shape

(2, 12)

In [60]:
l9.shape

(1, 12)

In [61]:
arr1=l9+l12

In [62]:
arr1

array([[ 3, 12, 10, 13, 16, 21, 21, 17, 20, 40, 33, 37],
       [15, 24, 22, 25, 28, 33, 33, 29, 32, 52, 45, 49]])

In [63]:
arr3=l9.reshape(1,12)

In [64]:
arr3

array([[ 2, 10,  7,  9, 11, 15, 14,  9, 11, 30, 22, 25]])

In [65]:
arr3.shape


(1, 12)

In [66]:
arr2 = l9+l7

In [67]:
arr2

array([[ 3, 12, 10, 13, 16, 21, 21, 17, 20, 40, 33, 37]])

In [68]:
l7.shape

(12,)

In [69]:
arr4=l7+l9

In [70]:
arr4

array([[ 3, 12, 10, 13, 16, 21, 21, 17, 20, 40, 33, 37]])

In [71]:
arr5 = arr4+arr3

In [72]:
arr5

array([[ 5, 22, 17, 22, 27, 36, 35, 26, 31, 70, 55, 62]])

In [73]:
arr6=l9.reshape(2,6)

In [74]:
arr7=l7.reshape(2,6)

In [75]:
arr8=arr6+arr7

In [76]:
arr8

array([[ 3, 12, 10, 13, 16, 21],
       [21, 17, 20, 40, 33, 37]])

zeros = it is used to make an array of values = 0

In [77]:
arr9 = np.zeros((2,10))

In [78]:
arr9

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [79]:
arr9=np.zeros((5,10),dtype=int)


In [80]:
arr9

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

ones = it is used to generate an array of ony unit digits .

In [81]:
arr = np.ones((9,15))

In [82]:
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

empty = it is used to get an array of randomly generated values or garbage values .

In [83]:
arr = np.empty((4,6))

In [84]:
arr

array([[1.92483933e-315, 0.00000000e+000, 3.45845952e-323,
        4.44659081e-323, 5.43472210e-323, 7.41098469e-323],
       [6.91691904e-323, 4.44659081e-323, 5.43472210e-323,
        1.48219694e-322, 1.08694442e-322, 1.23516411e-322],
       [9.88131292e-324, 4.94065646e-323, 3.45845952e-323,
        4.44659081e-323, 5.43472210e-323, 7.41098469e-323],
       [6.91691904e-323, 4.44659081e-323, 5.43472210e-323,
        1.48219694e-322, 1.08694442e-322, 1.23516411e-322]])

In [85]:
arr = np.empty((4,6),dtype=int)

In [86]:
arr 

array([[389591817,         0,         7,         9,        11,        15],
       [       14,         9,        11,        30,        22,        25],
       [        2,        10,         7,         9,        11,        15],
       [       14,         9,        11,        30,        22,        25]])

arange = it is used to get an array of desired staring point & ending point with how much differnce we want in the two values .

In [87]:
arr = np.arange(0,20,2.5,dtype=np.float64)

In [88]:
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5])

linspace = it is used to make an array of desired staring point & ending point with how much values we want then the funtion will generate the gap itself according to the values 

In [89]:
arr = np.linspace(0,10,20)

In [90]:
arr

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [91]:
arr = np.random.binomial(n=6,p=0.6,size=(2,5))

In [92]:
arr

array([[3, 4, 3, 6, 5],
       [4, 6, 2, 5, 2]])

In [93]:
arr = np.random.binomial(n=1,p=0.5,size=(2,5))

In [94]:
arr

array([[1, 0, 0, 0, 0],
       [1, 0, 0, 1, 1]])

In [95]:
arr = np.random.multivariate_normal(mean=[1,1,1,1],cov=[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]],size=10)

In [96]:
arr

array([[ 2.12940547, -0.42214904,  0.05350644,  0.87673452],
       [ 2.034211  ,  1.46242954,  2.5286751 ,  2.55449368],
       [-0.91800012,  1.71201374,  1.75256187,  0.60908948],
       [ 1.40305657,  0.2343812 ,  0.91817175,  0.41066017],
       [ 0.91391709,  1.50403638,  1.17568852,  0.78538502],
       [ 1.40443896,  1.29790579, -0.79852512,  1.07586389],
       [ 0.75799734,  0.04168457,  1.59932529,  1.36338189],
       [ 0.56104824,  1.71518475,  1.75525958, -0.90650888],
       [ 1.42899933,  0.33883351,  2.23120293,  0.38591563],
       [ 1.51130253,  0.92203578,  0.61414662, -1.72095803]])

In [97]:
arr = np.random.multivariate_normal(mean=[1,2,3,4],cov=[[1,0,0,0],[0,2,0,0],[0,0,3,0],[0,0,0,4]],size=10)

In [98]:
arr

array([[-0.14341546,  1.39262432,  2.59244874,  5.53258473],
       [ 0.90047161, -0.62013854,  3.78661025,  3.91020952],
       [ 0.40352353, -0.46658278,  3.55532316,  4.70858456],
       [ 2.22500998,  4.85796881,  0.41451017,  7.18197712],
       [ 1.94626834,  3.68079969,  3.01847012,  4.37862841],
       [ 1.45889047,  1.21095839,  1.02144256,  6.64805509],
       [ 1.94974536,  4.91230182,  0.82122841,  3.37334982],
       [ 1.07462124,  2.29852272,  3.25337825,  4.79670789],
       [ 1.47053337,  1.97454826,  2.40364852,  1.65178801],
       [ 0.5151637 ,  0.53582096,  2.46280426,  6.52727773]])

In [99]:
arr = np.random.normal(loc=5,scale=1,size=(2,10))

In [100]:
arr

array([[5.16324923, 5.96357476, 4.53813805, 6.43055982, 3.01740308,
        5.5550672 , 5.55382255, 3.04107527, 6.02777753, 5.87158708],
       [4.26068476, 3.61893608, 5.43149677, 3.30470086, 4.94784375,
        6.32631487, 5.77215603, 4.95427939, 5.69228014, 5.96850851]])

In [101]:
arr_mean=np.mean(arr)

In [102]:
arr_mean

np.float64(5.071972786007248)

In [105]:
arr = np.random.rand(10,10)

In [106]:
arr

array([[0.19023838, 0.28574127, 0.29990756, 0.98345713, 0.34578984,
        0.69966948, 0.91456279, 0.05013406, 0.93341654, 0.27324446],
       [0.13506362, 0.43036225, 0.73635103, 0.23811728, 0.83361065,
        0.33671312, 0.90758722, 0.66957731, 0.07997937, 0.48390872],
       [0.69160991, 0.41150656, 0.15659555, 0.29073685, 0.77891949,
        0.95896188, 0.29438247, 0.51398645, 0.90971218, 0.94112939],
       [0.19903106, 0.01450005, 0.56813243, 0.39264044, 0.019986  ,
        0.86496873, 0.17037414, 0.23813543, 0.72297342, 0.93278553],
       [0.18395477, 0.53946697, 0.66843991, 0.13802555, 0.58571368,
        0.45377082, 0.63313168, 0.74462827, 0.96262773, 0.78096586],
       [0.09451733, 0.57749177, 0.79369306, 0.83798174, 0.36883049,
        0.35996389, 0.88250417, 0.05105503, 0.49724489, 0.60515614],
       [0.59456504, 0.85757186, 0.89354537, 0.78567068, 0.4093605 ,
        0.15909368, 0.61058218, 0.16446934, 0.70061619, 0.51514476],
       [0.1522821 , 0.84072837, 0.6879879

In [107]:
arr = np.random.randint(low=10,high=25,size= (2,20))

In [108]:
arr

array([[16, 12, 24, 21, 24, 24, 21, 20, 22, 24, 19, 14, 13, 14, 16, 22,
        19, 14, 23, 18],
       [19, 17, 23, 13, 20, 24, 20, 22, 12, 20, 23, 17, 20, 19, 15, 11,
        24, 21, 18, 14]])

In [109]:
arr = np.random.randn(5,10)

In [110]:
arr

array([[ 6.15733198e-01,  4.67448486e-02,  6.59485361e-01,
        -2.92387484e-01, -7.51857872e-02,  7.46428206e-01,
         2.48108190e-01, -6.93330355e-01, -1.65589725e+00,
        -1.87792515e+00],
       [-1.54850255e+00, -2.02967669e-01, -1.16173665e+00,
         4.42753268e-01,  3.70899216e-01, -9.13768872e-01,
         5.72364202e-01, -1.82547198e-02, -1.14305610e+00,
        -1.56456714e+00],
       [-1.22318814e+00, -1.22640006e-01,  1.28143927e-02,
        -2.08198207e-01, -3.53430843e-02, -7.37307168e-01,
         7.26544267e-01, -8.16229367e-02,  7.32012697e-02,
         3.45194606e-01],
       [-2.54522624e+00,  4.28823502e-01,  6.02453423e-01,
         1.67207844e-01,  2.33165942e-01, -5.70890185e-01,
         6.04778673e-01, -9.96722923e-01, -7.18807403e-01,
         2.72481720e-02],
       [-1.44519538e+00,  1.04315555e-01,  3.19374799e-01,
         3.16515724e-01,  9.19242932e-01, -1.89928787e+00,
        -6.29989073e-01,  2.26812854e-03,  5.03337322e-01,
         1.