In [1]:
import numpy as np 

In [2]:
l = [1,2,3,6,5,4,8,7,9]
arr = np.array(l)
print(arr)

[1 2 3 6 5 4 8 7 9]


In [3]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [4]:
l2 = [[[1,2,3,],[4,5,6,],[7,8,9],[10,11,12]]]

In [5]:
l2

[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]]

In [6]:
np.shape(l2)

(1, 4, 3)

In [7]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [8]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [9]:
arr.shape

(9,)

In [10]:
l2 = np.reshape(l2,(3,2,2))

In [11]:
np.shape(l2)

(3, 2, 2)

In [12]:
print(l2)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [13]:
l2 [0,1,0]

np.int64(3)

In [14]:
l2 [0,0,0]

np.int64(1)

In [15]:
l2 [2,1,:]

array([11, 12])

In [16]:
l5 = [1,2,3,4,5,6,7,8,9,10]

In [17]:
l5

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [18]:
l5 * 2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [19]:
l5 = np.array(l5)

In [20]:
l5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
l5.shape

(10,)

In [22]:
l5 = l5.reshape(5,2)

In [23]:
l5

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [24]:
l6 = [1,2,3,4,5,6,7,8,9,10]

In [25]:
arr=np.array(l6)

In [26]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr* 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [28]:
arr + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [29]:
arr - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [30]:
arr.shape


(10,)

In [31]:
arr = arr.reshape(2,5)

In [32]:
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [33]:
l7 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [34]:
l7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [35]:
l7.shape

(12,)

In [36]:
l8 = np.array([1,8,4,5,6,9,7,1,2,20,11,13])

In [37]:
l8

array([ 1,  8,  4,  5,  6,  9,  7,  1,  2, 20, 11, 13])

In [38]:
l8.shape

(12,)

In [39]:
l8 = l8.reshape(1,12)

In [40]:
l8.shape

(1, 12)

In [41]:
l9 = l8 + l7

In [42]:
l9 

array([[ 2, 10,  7,  9, 11, 15, 14,  9, 11, 30, 22, 25]])

In [43]:
l9.shape

(1, 12)

In [44]:
l10 = np.array([1,5,8,7,4,6,9,2,3,6,5,4,7,8])

In [45]:
l10

array([1, 5, 8, 7, 4, 6, 9, 2, 3, 6, 5, 4, 7, 8])

In [46]:
l10.shape

(14,)

In [47]:
l10 = l10.reshape(14,1)

In [48]:
l11 = l10 + l7

In [49]:
l11

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [50]:
l12 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24])

In [51]:
l12 = l12.reshape(2,12)

In [52]:
l13 = l12 + l7

In [53]:
l13.shape

(2, 12)

In [54]:
l12 = l12.reshape(2,12)

In [55]:
l13 = l7 + l12

to add two matrix(array) we have to make their y-axis or columns of same value.

In [56]:
l13

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24],
       [14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36]])

In [57]:
l7.shape

(12,)

In [58]:
l12.shape

(2, 12)

In [59]:
l9.shape

(1, 12)

In [60]:
arr1=l9+l12

In [61]:
arr1

array([[ 3, 12, 10, 13, 16, 21, 21, 17, 20, 40, 33, 37],
       [15, 24, 22, 25, 28, 33, 33, 29, 32, 52, 45, 49]])

In [62]:
arr3=l9.reshape(1,12)

In [63]:
arr3

array([[ 2, 10,  7,  9, 11, 15, 14,  9, 11, 30, 22, 25]])

In [64]:
arr3.shape


(1, 12)

In [65]:
arr2 = l9+l7

In [66]:
arr2

array([[ 3, 12, 10, 13, 16, 21, 21, 17, 20, 40, 33, 37]])

In [67]:
l7.shape

(12,)

In [68]:
arr4=l7+l9

In [69]:
arr4

array([[ 3, 12, 10, 13, 16, 21, 21, 17, 20, 40, 33, 37]])

In [70]:
arr5 = arr4+arr3

In [71]:
arr5

array([[ 5, 22, 17, 22, 27, 36, 35, 26, 31, 70, 55, 62]])

In [72]:
arr6=l9.reshape(2,6)    

In [73]:
arr7=l7.reshape(2,6)

In [74]:
arr8=arr6+arr7

In [75]:
arr8

array([[ 3, 12, 10, 13, 16, 21],
       [21, 17, 20, 40, 33, 37]])

zeros = it is used to make an array of values = 0

In [76]:
arr9 = np.zeros((2,10))

In [141]:
arr = np.ones((4,8),dtype=int)

In [142]:
arr

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [148]:
arr = arr.reshape(8,1,1,1,1,1,1,4)

In [149]:
arr

array([[[[[[[[1, 1, 1, 1]]]]]]],






       [[[[[[[1, 1, 1, 1]]]]]]],






       [[[[[[[1, 1, 1, 1]]]]]]],






       [[[[[[[1, 1, 1, 1]]]]]]],






       [[[[[[[1, 1, 1, 1]]]]]]],






       [[[[[[[1, 1, 1, 1]]]]]]],






       [[[[[[[1, 1, 1, 1]]]]]]],






       [[[[[[[1, 1, 1, 1]]]]]]]])

In [77]:
arr9

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [78]:
arr9=np.zeros((5,10),dtype=int)


In [79]:
arr9

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

ones = it is used to generate an array of ony unit digits .

In [80]:
arr = np.ones((9,15))

In [81]:
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

empty = it is used to get an array of randomly generated values or garbage values .

In [82]:
arr = np.empty((4,6))

In [83]:
arr

array([[3.70401858e-315, 0.00000000e+000, 3.45845952e-323,
        4.44659081e-323, 5.43472210e-323, 7.41098469e-323],
       [6.91691904e-323, 4.44659081e-323, 5.43472210e-323,
        1.48219694e-322, 1.08694442e-322, 1.23516411e-322],
       [9.88131292e-324, 4.94065646e-323, 3.45845952e-323,
        4.44659081e-323, 5.43472210e-323, 7.41098469e-323],
       [6.91691904e-323, 4.44659081e-323, 5.43472210e-323,
        1.48219694e-322, 1.08694442e-322, 1.23516411e-322]])

In [84]:
arr = np.empty((4,6),dtype=int)

In [85]:
arr 

array([[749701707,         0,         7,         9,        11,        15],
       [       14,         9,        11,        30,        22,        25],
       [        2,        10,         7,         9,        11,        15],
       [       14,         9,        11,        30,        22,        25]])

arange = it is used to get an array of desired staring point & ending point with how much differnce we want in the two values .

In [86]:
arr = np.arange(0,20,2.5,dtype=np.float64)

In [87]:
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5])

linspace = it is used to make an array of desired staring point & ending point with how much values we want then the funtion will generate the gap itself according to the values 

In [88]:
arr = np.linspace(0,10,20)

In [89]:
arr

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [90]:
arr = np.random.binomial(n=6,p=0.6,size=(2,5))

In [91]:
arr

array([[5, 6, 4, 2, 5],
       [3, 4, 5, 3, 4]])

In [92]:
arr = np.random.binomial(n=1,p=0.5,size=(2,5))

In [93]:
arr

array([[1, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [94]:
arr = np.random.multivariate_normal(mean=[1,1,1,1],cov=[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]],size=10)

In [95]:
arr

array([[ 3.01032396,  1.73212656, -1.0342936 ,  0.01236265],
       [ 3.12989305,  1.05267617,  0.41578984,  1.03557332],
       [ 2.80382033,  1.07219392,  0.46018547,  1.17862549],
       [ 2.1238067 ,  2.40417933,  1.98407812,  0.83730025],
       [ 0.3690314 ,  1.48268382,  1.47213543,  1.72690413],
       [-0.41855185, -0.17926819,  1.68786236,  0.50631412],
       [ 1.33254346,  0.89210512,  1.99666804,  3.69552757],
       [ 0.57302779,  0.86956439,  0.09677798,  2.00675157],
       [ 1.4365046 ,  0.80732382,  1.9355582 ,  0.0251639 ],
       [ 3.76571991, -0.98583067,  2.33693508,  1.57770308]])

In [96]:
arr = np.random.multivariate_normal(mean=[1,2,3,4],cov=[[1,0,0,0],[0,2,0,0],[0,0,3,0],[0,0,0,4]],size=10)

In [97]:
arr

array([[ 0.34867111,  1.42944271,  3.25790664,  5.86770015],
       [ 2.14170134,  1.31681486,  2.91102336,  7.50056508],
       [ 1.79594713,  1.96329587,  6.80844114,  4.69455036],
       [ 1.46794026,  2.89123281,  2.62191929,  8.05995494],
       [-1.23447912,  2.10882568,  5.81394684,  4.64893342],
       [ 2.17647331,  2.23901671,  4.4783167 ,  5.18391536],
       [ 0.09014581, -0.80378785,  3.33531585,  6.07540375],
       [ 1.80965063,  2.18311326,  3.20789784,  5.72622545],
       [ 1.42404117,  3.29068158,  3.75267696,  5.73725039],
       [ 2.835248  ,  3.19663734,  2.03713307,  4.08939976]])

In [98]:
arr = np.random.normal(loc=5,scale=1,size=(2,10))

In [99]:
arr

array([[5.75403745, 2.55198188, 5.97391076, 4.76562596, 5.41863948,
        5.57150607, 4.50696035, 4.51563596, 4.40272973, 4.09000048],
       [4.04857696, 5.91605902, 6.31235566, 6.40746086, 6.50957504,
        6.47105742, 2.88468131, 4.37279122, 2.90653076, 5.7361838 ]])

In [100]:
arr_mean=np.mean(arr)

In [101]:
arr_mean

np.float64(4.955815008318452)

In [102]:
arr = np.random.rand(10,10)

In [103]:
arr

array([[0.13150833, 0.23876145, 0.43469879, 0.18237559, 0.20802554,
        0.31733377, 0.40152987, 0.56065929, 0.3417839 , 0.39308883],
       [0.93439903, 0.84747022, 0.73194477, 0.81759529, 0.78962049,
        0.9814536 , 0.73737436, 0.21496806, 0.00731738, 0.89134007],
       [0.82701812, 0.25073745, 0.13365093, 0.13091894, 0.25522869,
        0.1069904 , 0.71998395, 0.89461792, 0.51921553, 0.52176642],
       [0.59482618, 0.47460474, 0.77873175, 0.48458074, 0.21966891,
        0.95562623, 0.9251241 , 0.82143562, 0.51739962, 0.44898125],
       [0.25838719, 0.19945825, 0.17019276, 0.65124408, 0.61250801,
        0.56218121, 0.00325091, 0.73297295, 0.84733595, 0.48007361],
       [0.54184042, 0.13521883, 0.34722743, 0.99256347, 0.85636205,
        0.14866691, 0.73999342, 0.77885217, 0.12750552, 0.1655733 ],
       [0.33235902, 0.03700285, 0.68535464, 0.38876298, 0.76501829,
        0.03299453, 0.6573366 , 0.25111498, 0.32884369, 0.56817245],
       [0.58520061, 0.38348418, 0.1362137

In [104]:
arr = np.random.randint(low=10,high=25,size= (2,20))

In [105]:
arr

array([[20, 24, 24, 10, 19, 12, 12, 10, 18, 15, 14, 21, 12, 16, 16, 20,
        13, 11, 18, 15],
       [14, 13, 17, 19, 12, 16, 16, 16, 19, 24, 20, 13, 20, 23, 21, 21,
        11, 22, 15, 13]])

In [106]:
arr = np.random.randn(5,10)

In [107]:
arr

array([[ 1.77831903e+00,  2.31032769e-01, -1.44412548e+00,
        -2.19277297e-01,  5.37659117e-01, -9.51786486e-01,
        -6.57014918e-01, -1.89560340e-01,  2.06155278e-01,
        -2.05144374e+00],
       [-5.00967969e-01, -1.83069968e+00, -2.60693259e-01,
         1.47754180e+00,  4.74565340e-01, -1.71591692e-01,
         2.65131439e-01,  7.43205236e-02, -1.34723502e-01,
        -9.00259633e-01],
       [-1.85919265e+00,  4.97096377e-01,  5.02748453e-01,
         3.84370470e-01, -1.16032658e-01, -2.73712399e-01,
         9.20413613e-01, -6.70826596e-01, -1.88128968e+00,
        -1.28691076e+00],
       [-5.23914004e-01, -3.82362883e-01,  1.89992334e-03,
        -5.78955765e-01,  1.73156473e+00, -7.56359008e-01,
         1.19729756e+00, -1.02780185e+00,  7.78717385e-01,
        -9.72408720e-01],
       [-3.85776781e-01,  5.19352803e-01,  1.77968953e-01,
         4.77055206e-01, -1.16259768e+00, -1.27600366e+00,
         1.06984022e+00, -6.16338563e-01, -1.38907882e-01,
        -5.

In [108]:
c = []

In [109]:
arr = np.array(c)

In [110]:
arr

array([], dtype=float64)

In [111]:
arr = np.zeros((0,0))

In [112]:
arr

array([], shape=(0, 0), dtype=float64)

In [113]:
arr = np.array((x:=[2,4,5,1,7,8,6,9,6,4]))

In [114]:
arr

array([2, 4, 5, 1, 7, 8, 6, 9, 6, 4])

eye - it create a numpy array having ones at diagonals.

In [115]:
arr = np.eye(3)

In [116]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [117]:
arr = np.eye(5,6)

In [118]:
arr

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [119]:
arr = np.eye(6,4)

In [120]:
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

logspace - it is used to generate a set of number whose ratio is same not difference in log scale.

In [121]:
arr = np.logspace(start=-2,stop=3,base=10,num=5)

In [122]:
arr

array([1.00000000e-02, 1.77827941e-01, 3.16227766e+00, 5.62341325e+01,
       1.00000000e+03])

In [123]:
arr = np.logspace(start=-2,stop=3,base=2,num=6)

In [124]:
arr

array([0.25, 0.5 , 1.  , 2.  , 4.  , 8.  ])

concatenate = it is used to combine two numpy arrays in different axises and can concatenate multiple numpy arrays .

In [125]:
left_arr = np.random.binomial(n=7,p=0.4,size=(2,6))
right_arr = np.random.binomial(n=10,p=0.6,size=(2,6))

In [126]:
row_wise_concat_arr = np.concatenate((left_arr,right_arr),axis=0)
col_wise_concat_arr = np.concatenate((left_arr,right_arr),axis=1)


In [127]:
row_wise_concat_arr

array([[2, 3, 0, 3, 3, 4],
       [1, 2, 4, 1, 2, 1],
       [6, 4, 6, 8, 8, 5],
       [7, 5, 7, 7, 5, 5]])

In [128]:
col_wise_concat_arr

array([[2, 3, 0, 3, 3, 4, 6, 4, 6, 8, 8, 5],
       [1, 2, 4, 1, 2, 1, 7, 5, 7, 7, 5, 5]])

delete = it deletes the rows or columns or depths of which axises are given.(in this condition)

In [129]:
col_wise_concat_arr = np.delete(col_wise_concat_arr,[1,3],axis=1)

In [130]:
col_wise_concat_arr

array([[2, 0, 3, 4, 6, 4, 6, 8, 8, 5],
       [1, 4, 2, 1, 7, 5, 7, 7, 5, 5]])

In [131]:
row_wise_concat_arr = np.delete(row_wise_concat_arr,[1,3],axis=0)

In [132]:
row_wise_concat_arr

array([[2, 3, 0, 3, 3, 4],
       [6, 4, 6, 8, 8, 5]])

Done -> Concept of boolean masking in numpy arrays . 

In [133]:
bmask = np.ones((col_wise_concat_arr.shape[1],),dtype=bool)

In [134]:
bmask

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [135]:
bmask[1]=False
bmask[5]=False

In [136]:
bmask

array([ True, False,  True,  True,  True, False,  True,  True,  True,
        True])

In [137]:
col_wise_concat_arr[:,bmask]

array([[2, 3, 4, 6, 6, 8, 8, 5],
       [1, 2, 1, 7, 7, 7, 5, 5]])

In [138]:
bmask1=np.ones((row_wise_concat_arr.shape[0],),dtype=bool)

In [139]:
bmask1

array([ True,  True])

In [140]:
bmask1[1]=False
bmask1[3]=False

IndexError: index 3 is out of bounds for axis 0 with size 2

In [ ]:
bmask1

array([ True, False,  True, False])

In [ ]:
row_wise_concat_arr[bmask1,:]

array([[1, 4, 1, 3, 3, 2],
       [4, 9, 4, 7, 7, 5]])

In [ ]:
arr8=arr8.reshape(2,6)

In [ ]:
arr8

array([[ 3, 12, 10, 13, 16, 21],
       [21, 17, 20, 40, 33, 37]])

In [ ]:
arr8 = np.expand_dims(arr8,axis=1)

In [ ]:
arr8.shape

(2, 1, 6)

In [ ]:
arr8

array([[[ 3, 12, 10, 13, 16, 21]],

       [[21, 17, 20, 40, 33, 37]]])

In [ ]:
arr = np.random.randint(low=0,high=20,size=(1,2,3,4,5))

In [ ]:
arr

array([[[[[ 2,  8,  5,  2, 13],
          [14, 16,  9, 13, 19],
          [ 0, 16, 17,  1,  3],
          [11, 17,  2, 19, 18]],

         [[14,  7,  2,  5,  6],
          [ 0,  3, 12, 12, 14],
          [19, 11,  8,  2, 17],
          [15, 16,  1, 15, 19]],

         [[ 7,  6,  3,  7, 15],
          [ 4,  2,  3, 17,  7],
          [ 6,  0, 10,  2,  7],
          [18,  8,  4,  2, 13]]],


        [[[10,  4,  6, 14, 12],
          [17,  7,  0, 12, 18],
          [11,  2,  6, 11,  1],
          [15,  7,  2,  3, 18]],

         [[ 7, 19, 17,  2, 17],
          [16,  8, 16, 13,  4],
          [ 2,  5, 14, 19,  0],
          [ 4,  3,  5,  1,  5]],

         [[ 4, 19, 14,  7,  8],
          [16,  9,  8, 17, 14],
          [16,  5, 14,  7, 14],
          [ 5, 17,  1,  2,  6]]]]])

In [ ]:
arr.shape

(1, 2, 3, 4, 5)

Inserting new axes into a NumPy array, concept of ellipsis as well as it's notation.

In [ ]:
arr = arr[:,:,np.newaxis,...]

In [ ]:
arr.shape

(1, 2, 1, 3, 4, 5)

squeeze = it is used to squeeze the size of an array by removing all 1 .

In [ ]:
squeezed_arr=np.squeeze(arr)

In [ ]:
squeezed_arr.shape

(2, 3, 4, 5)

ravel = it is used to make a single dimnesion array with all the elements .

In [ ]:
flattened_arr = np.ravel(squeezed_arr)

In [ ]:
flattened_arr.shape

(120,)

reshape = it is used to reshape an array in different dimensions but the no. of elements should be same.

In [ ]:
reshaped_arr = np.reshape(squeezed_arr,newshape=(3,5,4,1,2))

/tmp/ipykernel_2365/1100543301.py:1: DeprecationWarning: `newshape` keyword argument is deprecated, use `shape=...` or pass shape positionally instead. (deprecated in NumPy 2.1)
  reshaped_arr = np.reshape(squeezed_arr,newshape=(3,5,4,1,2))


In [ ]:
reshaped_arr.shape

(3, 5, 4, 1, 2)

In [ ]:
reshaped_arr = np.reshape(squeezed_arr,newshape=(15,1,8))

/tmp/ipykernel_2365/1744322687.py:1: DeprecationWarning: `newshape` keyword argument is deprecated, use `shape=...` or pass shape positionally instead. (deprecated in NumPy 2.1)
  reshaped_arr = np.reshape(squeezed_arr,newshape=(15,1,8))


In [ ]:
reshaped_arr.shape

(15, 1, 8)

In [ ]:
reshaped_arr = np.reshape(squeezed_arr,newshape=(120,))

/tmp/ipykernel_2365/4254991431.py:1: DeprecationWarning: `newshape` keyword argument is deprecated, use `shape=...` or pass shape positionally instead. (deprecated in NumPy 2.1)
  reshaped_arr = np.reshape(squeezed_arr,newshape=(120,))


In [ ]:
reshaped_arr.shape

(120,)

In [ ]:
arr = np.random.randint(low=0,hogh=20,size=10)

In [ ]:
arr

array([0.25, 0.5 , 1.  , 2.  , 4.  , 8.  ])

padding = it is used to add values on the basis of applications. now I have used padding for 1d-array.

In [ ]:
padded_arr=np.pad(arr,pad_width=(0,5),mode='constant',constant_values=0)

In [ ]:
padded_arr

array([0.25, 0.5 , 1.  , 2.  , 4.  , 8.  , 0.  , 0.  , 0.  , 0.  , 0.  ])

In [ ]:
padded_arr1 = np.pad(arr,pad_width=(5,0),mode='edge')

In [ ]:
padded_arr1

array([0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.5 , 1.  , 2.  , 4.  , 8.  ])

In [ ]:
padded_arr = np.pad(arr,pad_width=(2,3),mode='linear_ramp',end_values=(0.05,12))

In [ ]:
padded_arr

array([ 0.05      ,  0.15      ,  0.25      ,  0.5       ,  1.        ,
        2.        ,  4.        ,  8.        ,  9.33333333, 10.66666667,
       12.        ])

In [ ]:
padded_arr = np.pad(arr,pad_width=(3,2),mode='mean')

In [ ]:
padded_arr

array([2.625, 2.625, 2.625, 0.25 , 0.5  , 1.   , 2.   , 4.   , 8.   ,
       2.625, 2.625])

In [ ]:
padded_arr = np.pad(arr,pad_width=(2,3),mode='reflect')

In [ ]:
padded_arr

array([1.  , 0.5 , 0.25, 0.5 , 1.  , 2.  , 4.  , 8.  , 4.  , 2.  , 1.  ])