In [45]:
import numpy as np 

In [46]:
l = [1,2,3,6,5,4,8,7,9]
arr = np.array(l)
print(arr)

[1 2 3 6 5 4 8 7 9]


In [47]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [48]:
l2 = [[[1,2,3,],[4,5,6,],[7,8,9],[10,11,12]]]

In [49]:
l2

[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]]

In [50]:
np.shape(l2)

(1, 4, 3)

In [51]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [52]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [53]:
arr.shape

(9,)

In [54]:
l2 = np.reshape(l2,(3,2,2))

In [55]:
np.shape(l2)

(3, 2, 2)

In [56]:
print(l2)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [57]:
l2 [0,1,0]

np.int64(3)

In [58]:
l2 [0,0,0]

np.int64(1)

In [59]:
l2 [2,1,:]

array([11, 12])

In [60]:
l5 = [1,2,3,4,5,6,7,8,9,10]

In [61]:
l5

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [62]:
l5 * 2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [63]:
l5 = np.array(l5)

In [64]:
l5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
l5.shape

(10,)

In [66]:
l5 = l5.reshape(5,2)

In [67]:
l5

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [68]:
l6 = [1,2,3,4,5,6,7,8,9,10]

In [69]:
arr=np.array(l6)

In [70]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
arr* 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [72]:
arr + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [73]:
arr - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [74]:
arr.shape


(10,)

In [75]:
arr = arr.reshape(2,5)

In [76]:
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [77]:
l7 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [78]:
l7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [79]:
l7.shape

(12,)

In [80]:
l8 = np.array([1,8,4,5,6,9,7,1,2,20,11,13])

In [81]:
l8

array([ 1,  8,  4,  5,  6,  9,  7,  1,  2, 20, 11, 13])

In [82]:
l8.shape

(12,)

In [83]:
l8 = l8.reshape(1,12)

In [84]:
l8.shape

(1, 12)

In [85]:
l9 = l8 + l7

In [86]:
l9 

array([[ 2, 10,  7,  9, 11, 15, 14,  9, 11, 30, 22, 25]])

In [87]:
l9.shape

(1, 12)

In [88]:
l10 = np.array([1,5,8,7,4,6,9,2,3,6,5,4,7,8])

In [89]:
l10

array([1, 5, 8, 7, 4, 6, 9, 2, 3, 6, 5, 4, 7, 8])

In [90]:
l10.shape

(14,)

In [91]:
l10 = l10.reshape(14,1)

In [92]:
l11 = l10 + l7

In [93]:
l11

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [94]:
l12 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24])

In [95]:
l12 = l12.reshape(2,12)

In [96]:
l13 = l12 + l7

In [97]:
l13.shape

(2, 12)

In [98]:
l12 = l12.reshape(2,12)

In [99]:
l13 = l7 + l12

to add two matrix(array) we have to make their y-axis or columns of same value.

In [100]:
l13

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24],
       [14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36]])