In [1]:
import numpy as np 

In [2]:
l = [1,2,3,6,5,4,8,7,9]
arr = np.array(l)
print(arr)

[1 2 3 6 5 4 8 7 9]


In [3]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [4]:
l2 = [[[1,2,3,],[4,5,6,],[7,8,9],[10,11,12]]]

In [5]:
l2

[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]]

In [6]:
np.shape(l2)

(1, 4, 3)

In [7]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [8]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [9]:
arr.shape

(9,)

In [10]:
l2 = np.reshape(l2,(3,2,2))

In [11]:
np.shape(l2)

(3, 2, 2)

In [12]:
print(l2)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [13]:
l2 [0,1,0]

np.int64(3)

In [14]:
l2 [0,0,0]

np.int64(1)

In [15]:
l2 [2,1,:]

array([11, 12])

In [16]:
l5 = [1,2,3,4,5,6,7,8,9,10]

In [17]:
l5

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [18]:
l5 * 2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [19]:
l5 = np.array(l5)

In [20]:
l5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
l5.shape

(10,)

In [22]:
l5 = l5.reshape(5,2)

In [23]:
l5

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [24]:
l6 = [1,2,3,4,5,6,7,8,9,10]

In [25]:
arr=np.array(l6)

In [26]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr* 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [28]:
arr + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [29]:
arr - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [30]:
arr.shape


(10,)

In [31]:
arr = arr.reshape(2,5)

In [32]:
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [33]:
l7 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [34]:
l7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [35]:
l7.shape

(12,)

In [36]:
l8 = np.array([1,8,4,5,6,9,7,1,2,20,11,13])

In [37]:
l8

array([ 1,  8,  4,  5,  6,  9,  7,  1,  2, 20, 11, 13])

In [38]:
l8.shape

(12,)

In [39]:
l8 = l8.reshape(1,12)

In [40]:
l8.shape

(1, 12)

In [41]:
l9 = l8 + l7

In [42]:
l9 

array([[ 2, 10,  7,  9, 11, 15, 14,  9, 11, 30, 22, 25]])

In [43]:
l9.shape

(1, 12)

In [44]:
l10 = np.array([1,5,8,7,4,6,9,2,3,6,5,4,7,8])

In [45]:
l10

array([1, 5, 8, 7, 4, 6, 9, 2, 3, 6, 5, 4, 7, 8])

In [46]:
l10.shape

(14,)

In [47]:
l10 = l10.reshape(14,1)

In [48]:
l11 = l10 + l7

In [49]:
l11

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [50]:
l12 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24])

In [51]:
l12 = l12.reshape(2,12)

In [52]:
l13 = l12 + l7

In [53]:
l13.shape

(2, 12)

In [54]:
l12 = l12.reshape(2,12)

In [55]:
l13 = l7 + l12

to add two matrix(array) we have to make their y-axis or columns of same value.

In [56]:
l13

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24],
       [14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36]])

In [57]:
l7.shape

(12,)

In [58]:
l12.shape

(2, 12)

In [59]:
l9.shape

(1, 12)

In [60]:
arr1=l9+l12

In [61]:
arr1

array([[ 3, 12, 10, 13, 16, 21, 21, 17, 20, 40, 33, 37],
       [15, 24, 22, 25, 28, 33, 33, 29, 32, 52, 45, 49]])

In [62]:
arr3=l9.reshape(1,12)

In [63]:
arr3

array([[ 2, 10,  7,  9, 11, 15, 14,  9, 11, 30, 22, 25]])

In [64]:
arr3.shape


(1, 12)

In [65]:
arr2 = l9+l7

In [66]:
arr2

array([[ 3, 12, 10, 13, 16, 21, 21, 17, 20, 40, 33, 37]])

In [67]:
l7.shape

(12,)

In [68]:
arr4=l7+l9

In [69]:
arr4

array([[ 3, 12, 10, 13, 16, 21, 21, 17, 20, 40, 33, 37]])

In [70]:
arr5 = arr4+arr3

In [71]:
arr5

array([[ 5, 22, 17, 22, 27, 36, 35, 26, 31, 70, 55, 62]])

In [72]:
arr6=l9.reshape(2,6)

In [73]:
arr7=l7.reshape(2,6)

In [74]:
arr8=arr6+arr7

In [75]:
arr8

array([[ 3, 12, 10, 13, 16, 21],
       [21, 17, 20, 40, 33, 37]])

zeros = it is used to make an array of values = 0

In [76]:
arr9 = np.zeros((2,10))

In [77]:
arr9

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [78]:
arr9=np.zeros((5,10),dtype=int)


In [79]:
arr9

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

ones = it is used to generate an array of ony unit digits .

In [80]:
arr = np.ones((9,15))

In [81]:
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

empty = it is used to get an array of randomly generated values or garbage values .

In [82]:
arr = np.empty((4,6))

In [83]:
arr

array([[1.12210483e-315, 0.00000000e+000, 3.45845952e-323,
        4.44659081e-323, 5.43472210e-323, 7.41098469e-323],
       [6.91691904e-323, 4.44659081e-323, 5.43472210e-323,
        1.48219694e-322, 1.08694442e-322, 1.23516411e-322],
       [9.88131292e-324, 4.94065646e-323, 3.45845952e-323,
        4.44659081e-323, 5.43472210e-323, 7.41098469e-323],
       [6.91691904e-323, 4.44659081e-323, 5.43472210e-323,
        1.48219694e-322, 1.08694442e-322, 1.23516411e-322]])

In [84]:
arr = np.empty((4,6),dtype=int)

In [85]:
arr 

array([[227116546,         0,         7,         9,        11,        15],
       [       14,         9,        11,        30,        22,        25],
       [        2,        10,         7,         9,        11,        15],
       [       14,         9,        11,        30,        22,        25]])

arange = it is used to get an array of desired staring point & ending point with how much differnce we want in the two values .

In [86]:
arr = np.arange(0,20,2.5,dtype=np.float64)

In [87]:
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5])

linspace = it is used to make an array of desired staring point & ending point with how much values we want then the funtion will generate the gap itself according to the values 

In [88]:
arr = np.linspace(0,10,20)

In [89]:
arr

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [90]:
arr = np.random.binomial(n=6,p=0.6,size=(2,5))

In [91]:
arr

array([[5, 4, 4, 1, 4],
       [6, 4, 4, 2, 3]])

In [92]:
arr = np.random.binomial(n=1,p=0.5,size=(2,5))

In [93]:
arr

array([[1, 1, 1, 0, 1],
       [1, 0, 1, 1, 0]])

In [94]:
arr = np.random.multivariate_normal(mean=[1,1,1,1],cov=[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]],size=10)

In [95]:
arr

array([[ 0.61566174,  1.43054308,  0.30333534,  1.70094101],
       [ 0.61903466,  1.98716706,  1.45796598,  0.64196383],
       [ 1.86779668,  0.22265996,  2.43888514,  1.31709853],
       [ 1.23898688,  0.44568079,  1.42271403,  1.24710431],
       [ 1.18782124,  1.10993167,  0.09081651,  0.28853877],
       [ 0.88574309,  1.80900969,  0.68200152,  0.12576246],
       [-1.11127343,  1.56372505,  1.10181448,  0.16657756],
       [ 2.30239789,  0.32403268,  0.26310389,  1.30724951],
       [ 1.54640607,  2.03376979,  1.41389878,  1.1230879 ],
       [ 0.94185752,  2.54033144,  1.08931539,  1.51248369]])

In [96]:
arr = np.random.multivariate_normal(mean=[1,2,3,4],cov=[[1,0,0,0],[0,2,0,0],[0,0,3,0],[0,0,0,4]],size=10)

In [97]:
arr

array([[ 1.87639256,  6.27940889,  3.38741452,  7.73543852],
       [ 0.53280331,  0.21575115,  3.21357637,  5.79774174],
       [ 1.06693621,  3.7993698 ,  1.74316395,  4.13474787],
       [ 1.01796061,  2.15659067,  0.97208004,  4.64519071],
       [ 0.76739249,  3.11673827,  5.01852335,  4.88353946],
       [ 1.00920645,  4.87761507,  0.83863697,  9.86345902],
       [ 1.00214954,  1.68377263,  3.84290488,  3.9158078 ],
       [ 0.9598046 ,  2.18173886,  5.86782229,  2.33065747],
       [ 1.72388509,  2.89047314,  4.11413738,  3.04030111],
       [ 0.60209467,  1.76075342, -1.04665466,  0.6441548 ]])

In [98]:
arr = np.random.normal(loc=5,scale=1,size=(2,10))

In [99]:
arr

array([[5.19078559, 1.96428673, 4.91387224, 5.67141371, 5.94777894,
        5.27888011, 3.3500906 , 5.04336753, 4.05939097, 3.98106745],
       [5.64348718, 5.02573302, 6.63900785, 4.60172949, 3.312397  ,
        6.29630212, 4.52823706, 4.2352993 , 5.03237153, 6.00595789]])

In [100]:
arr_mean=np.mean(arr)

In [101]:
arr_mean

np.float64(4.83607281607196)

In [102]:
arr = np.random.rand(10,10)

In [103]:
arr

array([[0.33399731, 0.64863967, 0.10793022, 0.98458013, 0.65763952,
        0.68747454, 0.72529019, 0.86930329, 0.26669857, 0.56653412],
       [0.52228133, 0.76858435, 0.07855203, 0.47150486, 0.72115672,
        0.58924365, 0.29033852, 0.47188311, 0.36174501, 0.49676513],
       [0.86200993, 0.25664286, 0.10237544, 0.58807374, 0.22217001,
        0.45641331, 0.28101317, 0.97476523, 0.1835451 , 0.21052587],
       [0.77723798, 0.71827811, 0.48007238, 0.54277999, 0.57252478,
        0.39618666, 0.02318777, 0.73649338, 0.83124359, 0.11566843],
       [0.37553991, 0.52207171, 0.78562754, 0.87281551, 0.54779892,
        0.38730571, 0.71559199, 0.87329672, 0.01469491, 0.62156603],
       [0.22916046, 0.60420034, 0.82513953, 0.19527903, 0.98135251,
        0.43338715, 0.57102252, 0.54288502, 0.52618535, 0.10303745],
       [0.34533022, 0.92986434, 0.06939622, 0.43104569, 0.3498432 ,
        0.28232521, 0.20509129, 0.22635207, 0.11005034, 0.11774164],
       [0.03394488, 0.21333555, 0.3034849

In [104]:
arr = np.random.randint(low=10,high=25,size= (2,20))

In [105]:
arr

array([[11, 15, 14, 14, 19, 24, 15, 10, 16, 21, 19, 23, 16, 15, 24, 22,
        21, 23, 10, 14],
       [10, 23, 23, 23, 17, 12, 15, 23, 16, 18, 22, 12, 22, 19, 19, 17,
        16, 18, 16, 14]])

In [106]:
arr = np.random.randn(5,10)

In [107]:
arr

array([[-0.42157615, -0.17344396,  0.95835558, -1.01639896, -1.07232128,
        -0.09318924,  0.32211751, -2.23620398,  0.42760936,  0.85435811],
       [-1.37963004,  0.50376379,  0.53699242,  0.82196075, -0.10731041,
        -0.71562116, -1.02881222, -0.69500253,  1.52858006,  0.37417493],
       [ 1.85779206, -0.70496827,  0.95175556,  0.26109505,  0.30123508,
         0.4784732 ,  0.78278837,  0.04388642, -0.98750579,  0.44957398],
       [ 1.5753308 , -0.28794954,  0.51578857, -1.95011395, -0.4680552 ,
         1.07752274, -0.79739725, -1.11663959,  0.36893872, -1.12918473],
       [ 0.91480087,  0.04281512,  0.52791711,  2.06098357,  0.9244508 ,
        -0.99829824,  0.92943256, -1.15928915, -0.54849993, -1.06298902]])

In [108]:
c = []

In [109]:
arr = np.array(c)

In [110]:
arr

array([], dtype=float64)

In [111]:
arr = np.zeros((0,0))

In [112]:
arr

array([], shape=(0, 0), dtype=float64)

In [119]:
arr = np.array((x:=[2,4,5,1,7,8,6,9,6,4]))

In [120]:
arr

array([2, 4, 5, 1, 7, 8, 6, 9, 6, 4])

eye - it create a numpy array having ones at diagonals.

In [121]:
arr = np.eye(3)

In [122]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [130]:
arr = np.eye(5,6)

In [131]:
arr

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [132]:
arr = np.eye(6,4)

In [133]:
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

logspace - it is used to generate a set of number whose ratio is same not difference in log scale.

In [134]:
arr = np.logspace(start=-2,stop=3,base=10,num=5)

In [135]:
arr

array([1.00000000e-02, 1.77827941e-01, 3.16227766e+00, 5.62341325e+01,
       1.00000000e+03])

In [138]:
arr = np.logspace(start=-2,stop=3,base=2,num=6)

In [139]:
arr

array([0.25, 0.5 , 1.  , 2.  , 4.  , 8.  ])