In [20]:
import numpy as np 

In [21]:
l = [1,2,3,6,5,4,8,7,9]
arr = np.array(l)
print(arr)

[1 2 3 6 5 4 8 7 9]


In [22]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [23]:
l2 = [[[1,2,3,],[4,5,6,],[7,8,9]]]

In [24]:
l2

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]

In [25]:
arr1=np.shape(l2)

In [26]:
arr1

(1, 3, 3)

In [27]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [28]:
arr.shape

(9,)

In [31]:
l2 = np.reshape(l2,(3,3,1))

In [32]:
np.shape(l2)

(3, 3, 1)

In [33]:
print(l2)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
