In [2]:
import numpy as np 

In [3]:
l = [1,2,3,6,5,4,8,7,9]
arr = np.array(l)
print(arr)

[1 2 3 6 5 4 8 7 9]


In [4]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [5]:
l2 = [[[1,2,3,],[4,5,6,],[7,8,9],[10,11,12]]]

In [6]:
l2

[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]]

In [7]:
np.shape(l2)

(1, 4, 3)

In [8]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [9]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [10]:
arr.shape

(9,)

In [11]:
l2 = np.reshape(l2,(3,2,2))

In [12]:
np.shape(l2)

(3, 2, 2)

In [13]:
print(l2)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [14]:
l2 [0,1,0]

np.int64(3)

In [15]:
l2 [0,0,0]

np.int64(1)

In [16]:
l2 [2,1,:]

array([11, 12])

In [17]:
l5 = [1,2,3,4,5,6,7,8,9,10]

In [18]:
l5

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [19]:
l5 * 2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [20]:
l5 = np.array(l5)

In [21]:
l5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
l5.shape

(10,)

In [23]:
l5 = l5.reshape(5,2)

In [24]:
l5

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [25]:
l6 = [1,2,3,4,5,6,7,8,9,10]

In [26]:
arr=np.array(l6)

In [27]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr* 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [29]:
arr + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [30]:
arr - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [31]:
arr.shape


(10,)

In [32]:
arr = arr.reshape(2,5)

In [33]:
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [34]:
l7 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [35]:
l7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
l7.shape

(12,)

In [37]:
l8 = np.array([1,8,4,5,6,9,7,1,2,20,11,13])

In [38]:
l8

array([ 1,  8,  4,  5,  6,  9,  7,  1,  2, 20, 11, 13])

In [39]:
l8.shape

(12,)

In [40]:
l8 = l8.reshape(1,12)

In [41]:
l8.shape

(1, 12)

In [42]:
l9 = l8 + l7

In [43]:
l9 

array([[ 2, 10,  7,  9, 11, 15, 14,  9, 11, 30, 22, 25]])

In [44]:
l9.shape

(1, 12)

In [45]:
l10 = np.array([1,5,8,7,4,6,9,2,3,6,5,4,7,8])

In [46]:
l10

array([1, 5, 8, 7, 4, 6, 9, 2, 3, 6, 5, 4, 7, 8])

In [47]:
l10.shape

(14,)

In [48]:
l10 = l10.reshape(14,1)

In [49]:
l11 = l10 + l7

In [50]:
l11

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [51]:
l12 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24])

In [52]:
l12 = l12.reshape(2,12)

In [53]:
l13 = l12 + l7

In [54]:
l13.shape

(2, 12)

In [55]:
l12 = l12.reshape(2,12)

In [56]:
l13 = l7 + l12

to add two matrix(array) we have to make their y-axis or columns of same value.

In [57]:
l13

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24],
       [14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36]])

In [58]:
l7.shape

(12,)

In [59]:
l12.shape

(2, 12)

In [60]:
l9.shape

(1, 12)

In [61]:
arr1=l9+l12

In [62]:
arr1

array([[ 3, 12, 10, 13, 16, 21, 21, 17, 20, 40, 33, 37],
       [15, 24, 22, 25, 28, 33, 33, 29, 32, 52, 45, 49]])

In [63]:
arr3=l9.reshape(1,12)

In [64]:
arr3

array([[ 2, 10,  7,  9, 11, 15, 14,  9, 11, 30, 22, 25]])

In [65]:
arr3.shape


(1, 12)

In [66]:
arr2 = l9+l7

In [67]:
arr2

array([[ 3, 12, 10, 13, 16, 21, 21, 17, 20, 40, 33, 37]])

In [68]:
l7.shape

(12,)

In [69]:
arr4=l7+l9

In [70]:
arr4

array([[ 3, 12, 10, 13, 16, 21, 21, 17, 20, 40, 33, 37]])

In [71]:
arr5 = arr4+arr3

In [72]:
arr5

array([[ 5, 22, 17, 22, 27, 36, 35, 26, 31, 70, 55, 62]])

In [73]:
arr6=l9.reshape(2,6)

In [74]:
arr7=l7.reshape(2,6)

In [75]:
arr8=arr6+arr7

In [76]:
arr8

array([[ 3, 12, 10, 13, 16, 21],
       [21, 17, 20, 40, 33, 37]])

In [77]:
arr9 = np.zeros((2,10))

In [78]:
arr9

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [79]:
arr9=np.zeros((5,10),dtype=int)


In [80]:
arr9

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])