In [78]:
import numpy as np 

In [79]:
l = [1,2,3,6,5,4,8,7,9]
arr = np.array(l)
print(arr)

[1 2 3 6 5 4 8 7 9]


In [80]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [81]:
l2 = [[[1,2,3,],[4,5,6,],[7,8,9],[10,11,12]]]

In [82]:
l2

[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]]

In [83]:
np.shape(l2)

(1, 4, 3)

In [84]:
arr1

(1, 3, 3)

In [85]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [86]:
arr.shape

(9,)

In [87]:
l2 = np.reshape(l2,(3,2,2))

In [88]:
np.shape(l2)

(3, 2, 2)

In [89]:
print(l2)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [90]:
l2 [0,1,0]

np.int64(3)

In [91]:
l2 [0,0,0]

np.int64(1)

In [92]:
l2 [2,1,:]

array([11, 12])

In [93]:
l5 = [1,2,3,4,5,6,7,8,9,10]

In [94]:
l5

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [95]:
l5 * 2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [96]:
l5 = np.array(l5)

In [97]:
l5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
l5.shape

(10,)

In [99]:
l5 = l5.reshape(5,2)

In [100]:
l5

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [101]:
l6 = [1,2,3,4,5,6,7,8,9,10]

In [102]:
arr=np.array(l6)

In [103]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [104]:
arr* 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [105]:
arr + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [106]:
arr - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [107]:
arr.shape


(10,)

In [108]:
arr = arr.reshape(2,5)

In [109]:
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])