In [1]:
import numpy as np 

In [21]:
l = [1,2,3,6,5,4,8,7,9]
arr = np.array(l)
print(arr)

[1 2 3 6 5 4 8 7 9]


In [22]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [23]:
l2 = [[[1,2,3,],[4,5,6,],[7,8,9],[10,11,12]]]

In [24]:
l2

[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]]

In [25]:
np.shape(l2)

(1, 4, 3)

In [26]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [27]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [28]:
arr.shape

(9,)

In [29]:
l2 = np.reshape(l2,(3,2,2))

In [30]:
np.shape(l2)

(3, 2, 2)

In [31]:
print(l2)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [32]:
l2 [0,1,0]

np.int64(3)

In [33]:
l2 [0,0,0]

np.int64(1)

In [34]:
l2 [2,1,:]

array([11, 12])

In [35]:
l5 = [1,2,3,4,5,6,7,8,9,10]

In [36]:
l5

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [37]:
l5 * 2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [38]:
l5 = np.array(l5)

In [39]:
l5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
l5.shape

(10,)

In [41]:
l5 = l5.reshape(5,2)

In [42]:
l5

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [43]:
l6 = [1,2,3,4,5,6,7,8,9,10]

In [44]:
arr=np.array(l6)

In [45]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr* 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [47]:
arr + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [48]:
arr - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [49]:
arr.shape


(10,)

In [50]:
arr = arr.reshape(2,5)

In [51]:
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [52]:
l7 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [53]:
l7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [54]:
l7.shape

(12,)

In [55]:
l8 = np.array([1,8,4,5,6,9,7,1,2,20,11,13])

In [56]:
l8

array([ 1,  8,  4,  5,  6,  9,  7,  1,  2, 20, 11, 13])

In [57]:
l8.shape

(12,)

In [58]:
l8 = l8.reshape(1,12)

In [59]:
l8.shape

(1, 12)

In [60]:
l9 = l8 + l7

In [61]:
l9 

array([[ 2, 10,  7,  9, 11, 15, 14,  9, 11, 30, 22, 25]])

In [62]:
l9.shape

(1, 12)

In [63]:
l10 = np.array([1,5,8,7,4,6,9,2,3,6,5,4,7,8])

In [64]:
l10

array([1, 5, 8, 7, 4, 6, 9, 2, 3, 6, 5, 4, 7, 8])

In [65]:
l10.shape

(14,)

In [66]:
l10 = l10.reshape(14,1)

In [67]:
l11 = l10 + l7

In [68]:
l11

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [69]:
l12 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24])

In [70]:
l12 = l12.reshape(2,12)

In [71]:
l13 = l12 + l7

In [72]:
l13.shape

(2, 12)

In [73]:
l12 = l12.reshape(2,12)

In [74]:
l13 = l7 + l12

to add two matrix(array) we have to make their y-axis or columns of same value.

In [75]:
l13

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24],
       [14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36]])

In [76]:
l7.shape

(12,)

In [77]:
l12.shape

(2, 12)

In [78]:
l9.shape

(1, 12)

In [79]:
arr1=l9+l12

In [80]:
arr1

array([[ 3, 12, 10, 13, 16, 21, 21, 17, 20, 40, 33, 37],
       [15, 24, 22, 25, 28, 33, 33, 29, 32, 52, 45, 49]])

In [81]:
arr3=l9.reshape(1,12)

In [82]:
arr3

array([[ 2, 10,  7,  9, 11, 15, 14,  9, 11, 30, 22, 25]])

In [83]:
arr3.shape


(1, 12)

In [84]:
arr2 = l9+l7

In [85]:
arr2

array([[ 3, 12, 10, 13, 16, 21, 21, 17, 20, 40, 33, 37]])

In [86]:
l7.shape

(12,)

In [87]:
arr4=l7+l9

In [88]:
arr4

array([[ 3, 12, 10, 13, 16, 21, 21, 17, 20, 40, 33, 37]])

In [89]:
arr5 = arr4+arr3

In [90]:
arr5

array([[ 5, 22, 17, 22, 27, 36, 35, 26, 31, 70, 55, 62]])

In [91]:
arr6=l9.reshape(2,6)    

In [92]:
arr7=l7.reshape(2,6)

In [93]:
arr8=arr6+arr7

In [94]:
arr8

array([[ 3, 12, 10, 13, 16, 21],
       [21, 17, 20, 40, 33, 37]])

zeros = it is used to make an array of values = 0

In [95]:
arr9 = np.zeros((2,10))

In [96]:
arr = np.ones((4,8),dtype=int)

In [97]:
arr

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [98]:
arr = arr.reshape(8,1,1,1,1,1,1,4)

In [99]:
arr

array([[[[[[[[1, 1, 1, 1]]]]]]],






       [[[[[[[1, 1, 1, 1]]]]]]],






       [[[[[[[1, 1, 1, 1]]]]]]],






       [[[[[[[1, 1, 1, 1]]]]]]],






       [[[[[[[1, 1, 1, 1]]]]]]],






       [[[[[[[1, 1, 1, 1]]]]]]],






       [[[[[[[1, 1, 1, 1]]]]]]],






       [[[[[[[1, 1, 1, 1]]]]]]]])

In [100]:
arr9

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [101]:
arr9=np.zeros((5,10),dtype=int)


In [102]:
arr9

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

ones = it is used to generate an array of ony unit digits .

In [103]:
arr = np.ones((9,15))

In [104]:
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

empty = it is used to get an array of randomly generated values or garbage values .

In [105]:
arr = np.empty((4,6))

In [106]:
arr

array([[4.85778288e-315, 0.00000000e+000, 3.99284226e+252,
        2.18434079e-094, 5.50422993e+257, 4.11083865e+223],
       [4.77389672e+180, 3.04040186e+180, 4.16865237e+199,
        5.57102646e+228, 2.55330150e-086, 9.14291407e+135],
       [2.45906524e+204, 2.03889434e+180, 1.99108547e+209,
        2.56898236e+151, 1.69430015e-152, 5.30992040e+180],
       [7.23011111e+165, 1.23973013e+224, 1.46899930e+179,
        9.08367237e+223, 1.16466228e-028, 1.16455638e-028]])

In [107]:
arr = np.empty((4,6),dtype=int)

In [108]:
arr 

array([[          983226200,                   0, 8386104319403237434,
        3205763763201926495, 8462919272755196448, 7952352385297033573],
       [7310019855701254176, 7306934683318117473, 7593470703247179124,
        8029185179637525614, 3326301354893524334, 6640883606134813811],
       [7664950018409651310, 7304682900689612917, 7738135659887682936,
        6872321981970084455, 2336353788721113384, 7310601619042361183],
       [7088493625967206258, 7959390453599265633, 7287422520966209380,
        7957695015493526904, 4189038621173441375, 4189038148857704736]])

arange = it is used to get an array of desired staring point & ending point with how much differnce we want in the two values .

In [109]:
arr = np.arange(0,20,2.5,dtype=np.float64)

In [110]:
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5])

linspace = it is used to make an array of desired staring point & ending point with how much values we want then the funtion will generate the gap itself according to the values 

In [111]:
arr = np.linspace(0,10,20)

In [112]:
arr

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [113]:
arr = np.random.binomial(n=6,p=0.6,size=(2,5))

In [114]:
arr

array([[5, 4, 2, 3, 3],
       [4, 2, 4, 2, 3]])

In [115]:
arr = np.random.binomial(n=1,p=0.5,size=(2,5))

In [116]:
arr

array([[0, 0, 0, 1, 0],
       [1, 1, 1, 0, 1]])

In [117]:
arr = np.random.multivariate_normal(mean=[1,1,1,1],cov=[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]],size=10)

In [118]:
arr

array([[ 1.52253084,  0.40387887,  2.01886348, -0.13223004],
       [ 0.25163666,  2.52527036,  0.90995742,  0.57521903],
       [-0.1147295 ,  1.77616175,  0.70434586,  0.7595871 ],
       [ 1.40888904,  0.41757425, -0.78995422,  0.82341913],
       [ 2.33925048,  0.1112077 ,  0.19821657,  0.25432971],
       [ 1.70093894,  1.0364835 ,  0.12667161,  0.83379371],
       [-0.81821414,  0.76068932, -0.67854973,  3.01462985],
       [ 2.26141059, -0.12805587,  0.9423853 ,  0.30349392],
       [ 0.75752029,  3.41119307,  1.07983138, -0.56808402],
       [-2.37274499,  0.79453437, -0.7735865 ,  0.05204853]])

In [119]:
arr = np.random.multivariate_normal(mean=[1,2,3,4],cov=[[1,0,0,0],[0,2,0,0],[0,0,3,0],[0,0,0,4]],size=10)

In [120]:
arr

array([[ 0.8117703 ,  1.30144671,  3.8530649 ,  0.34008547],
       [ 1.03248566,  1.02412863,  3.8455288 ,  1.5088323 ],
       [ 0.86898109,  2.93701162, -0.38748626,  3.5550374 ],
       [ 3.20664068,  2.47413876,  5.07884824,  2.15451488],
       [ 1.13446983,  5.39228398,  3.46339873,  4.47022278],
       [ 1.46113033,  2.85786253,  2.30544885,  2.22718959],
       [-0.81450373,  2.29596918,  3.5819986 ,  1.53860024],
       [ 0.63288896,  4.29926419,  2.48985732,  6.96079219],
       [ 1.61433645, -0.55651517,  3.12819578,  8.78750267],
       [ 2.6183949 ,  0.31726694,  1.80010344,  0.15351936]])

In [121]:
arr = np.random.normal(loc=5,scale=1,size=(2,10))

In [122]:
arr

array([[4.02209853, 4.82504801, 5.18972944, 4.99505198, 4.96212479,
        5.9969164 , 5.27312669, 5.85858362, 5.18219236, 4.6268129 ],
       [5.2388194 , 4.27013967, 4.9886481 , 6.08343187, 4.95084369,
        5.31696104, 7.91092816, 4.97614613, 3.46511582, 5.63196002]])

In [123]:
arr_mean=np.mean(arr)

In [124]:
arr_mean

np.float64(5.1882339316656685)

In [125]:
arr = np.random.rand(10,10)

In [126]:
arr

array([[0.8270818 , 0.10126061, 0.54366874, 0.21801829, 0.70328566,
        0.65547299, 0.71222641, 0.55402236, 0.2541182 , 0.98702691],
       [0.57839451, 0.57109323, 0.49602266, 0.41140246, 0.61788302,
        0.32341063, 0.20356785, 0.2946211 , 0.6995974 , 0.78785247],
       [0.06928411, 0.50725305, 0.76298026, 0.96535232, 0.48200347,
        0.78045774, 0.30619668, 0.7090061 , 0.97583811, 0.71896786],
       [0.24199311, 0.92898934, 0.29109891, 0.89326774, 0.56062533,
        0.97441295, 0.23637564, 0.49000413, 0.32261951, 0.07607657],
       [0.18426356, 0.0071395 , 0.82148953, 0.35170841, 0.89046653,
        0.99586475, 0.95443582, 0.5105869 , 0.68640824, 0.43078268],
       [0.27929941, 0.31192045, 0.6646884 , 0.87806311, 0.87351741,
        0.34884239, 0.39393265, 0.84715123, 0.97477765, 0.98787346],
       [0.14343438, 0.1673219 , 0.50501524, 0.65226673, 0.48011572,
        0.5716611 , 0.4205713 , 0.1220737 , 0.16679907, 0.04159813],
       [0.63712048, 0.99254393, 0.4537719

In [127]:
arr = np.random.randint(low=10,high=25,size= (2,20))

In [128]:
arr

array([[13, 17, 19, 13, 17, 13, 16, 15, 14, 19, 19, 17, 16, 11, 10, 24,
        18, 24, 19, 15],
       [12, 16, 20, 24, 18, 15, 20, 18, 18, 19, 12, 13, 13, 21, 13, 23,
        17, 21, 17, 20]])

In [129]:
arr = np.random.randn(5,10)

In [130]:
arr

array([[-0.67508604, -0.61689957, -0.63811612,  0.07906632, -0.43434519,
         0.6917671 ,  0.45814076, -2.50263354, -1.2118349 ,  0.7107415 ],
       [-0.41968434, -0.92622609,  1.31056342,  1.25179175,  0.25810501,
         1.91453221, -0.70559542, -1.36287131,  0.69523507, -0.2889747 ],
       [-0.69722872, -0.47269579,  0.88233044, -0.11793716,  0.07606026,
        -0.1183797 , -0.80425075,  0.79844462, -1.63982036, -0.14606739],
       [ 0.77364511, -1.06446491,  1.38937358, -0.28210735,  1.90638106,
         0.46329448, -1.76486443,  0.57256856, -0.44827252, -0.95098322],
       [ 1.32171829, -0.61091472,  1.21708016, -0.1743117 ,  0.14008871,
        -0.9418035 ,  1.34050278, -1.013179  , -0.47119981, -0.36741636]])

In [131]:
c = []

In [132]:
arr = np.array(c)

In [133]:
arr

array([], dtype=float64)

In [134]:
arr = np.zeros((0,0))

In [135]:
arr

array([], shape=(0, 0), dtype=float64)

In [136]:
arr = np.array((x:=[2,4,5,1,7,8,6,9,6,4]))

In [137]:
arr

array([2, 4, 5, 1, 7, 8, 6, 9, 6, 4])

eye - it create a numpy array having ones at diagonals.

In [138]:
arr = np.eye(3)

In [139]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [140]:
arr = np.eye(5,6)

In [141]:
arr

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [142]:
arr = np.eye(6,4)

In [143]:
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

logspace - it is used to generate a set of number whose ratio is same not difference in log scale.

In [144]:
arr = np.logspace(start=-2,stop=3,base=10,num=5)

In [145]:
arr

array([1.00000000e-02, 1.77827941e-01, 3.16227766e+00, 5.62341325e+01,
       1.00000000e+03])

In [146]:
arr = np.logspace(start=-2,stop=3,base=2,num=6)

In [147]:
arr

array([0.25, 0.5 , 1.  , 2.  , 4.  , 8.  ])

concatenate = it is used to combine two numpy arrays in different axises and can concatenate multiple numpy arrays .

In [148]:
left_arr = np.random.binomial(n=7,p=0.4,size=(2,6))
right_arr = np.random.binomial(n=10,p=0.6,size=(2,6))

In [149]:
row_wise_concat_arr = np.concatenate((left_arr,right_arr),axis=0)
col_wise_concat_arr = np.concatenate((left_arr,right_arr),axis=1)


In [150]:
row_wise_concat_arr

array([[2, 1, 2, 4, 2, 2],
       [2, 5, 4, 1, 2, 2],
       [6, 6, 6, 7, 4, 7],
       [6, 6, 6, 6, 7, 5]])

In [151]:
col_wise_concat_arr

array([[2, 1, 2, 4, 2, 2, 6, 6, 6, 7, 4, 7],
       [2, 5, 4, 1, 2, 2, 6, 6, 6, 6, 7, 5]])

delete = it deletes the rows or columns or depths of which axises are given.(in this condition)

In [152]:
col_wise_concat_arr = np.delete(col_wise_concat_arr,[1,3],axis=1)

In [153]:
col_wise_concat_arr

array([[2, 2, 2, 2, 6, 6, 6, 7, 4, 7],
       [2, 4, 2, 2, 6, 6, 6, 6, 7, 5]])

In [154]:
row_wise_concat_arr = np.delete(row_wise_concat_arr,[1,3],axis=0)

In [155]:
row_wise_concat_arr

array([[2, 1, 2, 4, 2, 2],
       [6, 6, 6, 7, 4, 7]])

Done -> Concept of boolean masking in numpy arrays . 

In [156]:
bmask = np.ones((col_wise_concat_arr.shape[1],),dtype=bool)

In [157]:
bmask

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [158]:
bmask[1]=False
bmask[5]=False

In [159]:
bmask

array([ True, False,  True,  True,  True, False,  True,  True,  True,
        True])

In [160]:
col_wise_concat_arr[:,bmask]

array([[2, 2, 2, 6, 6, 7, 4, 7],
       [2, 2, 2, 6, 6, 6, 7, 5]])

In [161]:
bmask1=np.ones((row_wise_concat_arr.shape[0],),dtype=bool)

In [162]:
bmask1

array([ True,  True])

In [163]:
bmask1[1]=False
bmask1[3]=False

IndexError: index 3 is out of bounds for axis 0 with size 2

In [ ]:
bmask1

array([ True, False,  True, False])

In [ ]:
row_wise_concat_arr[bmask1,:]

array([[1, 4, 1, 3, 3, 2],
       [4, 9, 4, 7, 7, 5]])

In [ ]:
arr8=arr8.reshape(2,6)

In [ ]:
arr8

array([[ 3, 12, 10, 13, 16, 21],
       [21, 17, 20, 40, 33, 37]])

In [ ]:
arr8 = np.expand_dims(arr8,axis=1)

In [ ]:
arr8.shape

(2, 1, 6)

In [ ]:
arr8

array([[[ 3, 12, 10, 13, 16, 21]],

       [[21, 17, 20, 40, 33, 37]]])

In [ ]:
arr = np.random.randint(low=0,high=20,size=(1,2,3,4,5))

In [ ]:
arr

array([[[[[ 2,  8,  5,  2, 13],
          [14, 16,  9, 13, 19],
          [ 0, 16, 17,  1,  3],
          [11, 17,  2, 19, 18]],

         [[14,  7,  2,  5,  6],
          [ 0,  3, 12, 12, 14],
          [19, 11,  8,  2, 17],
          [15, 16,  1, 15, 19]],

         [[ 7,  6,  3,  7, 15],
          [ 4,  2,  3, 17,  7],
          [ 6,  0, 10,  2,  7],
          [18,  8,  4,  2, 13]]],


        [[[10,  4,  6, 14, 12],
          [17,  7,  0, 12, 18],
          [11,  2,  6, 11,  1],
          [15,  7,  2,  3, 18]],

         [[ 7, 19, 17,  2, 17],
          [16,  8, 16, 13,  4],
          [ 2,  5, 14, 19,  0],
          [ 4,  3,  5,  1,  5]],

         [[ 4, 19, 14,  7,  8],
          [16,  9,  8, 17, 14],
          [16,  5, 14,  7, 14],
          [ 5, 17,  1,  2,  6]]]]])

In [ ]:
arr.shape

(1, 2, 3, 4, 5)

Inserting new axes into a NumPy array, concept of ellipsis as well as it's notation.

In [ ]:
arr = arr[:,:,np.newaxis,...]

In [ ]:
arr.shape

(1, 2, 1, 3, 4, 5)

squeeze = it is used to squeeze the size of an array by removing all 1 .

In [ ]:
squeezed_arr=np.squeeze(arr)

In [ ]:
squeezed_arr.shape

(2, 3, 4, 5)

ravel = it is used to make a single dimnesion array with all the elements .

In [ ]:
flattened_arr = np.ravel(squeezed_arr)

In [ ]:
flattened_arr.shape

(120,)

reshape = it is used to reshape an array in different dimensions but the no. of elements should be same.

In [ ]:
reshaped_arr = np.reshape(squeezed_arr,newshape=(3,5,4,1,2))

/tmp/ipykernel_2365/1100543301.py:1: DeprecationWarning: `newshape` keyword argument is deprecated, use `shape=...` or pass shape positionally instead. (deprecated in NumPy 2.1)
  reshaped_arr = np.reshape(squeezed_arr,newshape=(3,5,4,1,2))


In [ ]:
reshaped_arr.shape

(3, 5, 4, 1, 2)

In [ ]:
reshaped_arr = np.reshape(squeezed_arr,newshape=(15,1,8))

/tmp/ipykernel_2365/1744322687.py:1: DeprecationWarning: `newshape` keyword argument is deprecated, use `shape=...` or pass shape positionally instead. (deprecated in NumPy 2.1)
  reshaped_arr = np.reshape(squeezed_arr,newshape=(15,1,8))


In [ ]:
reshaped_arr.shape

(15, 1, 8)

In [ ]:
reshaped_arr = np.reshape(squeezed_arr,newshape=(120,))

/tmp/ipykernel_2365/4254991431.py:1: DeprecationWarning: `newshape` keyword argument is deprecated, use `shape=...` or pass shape positionally instead. (deprecated in NumPy 2.1)
  reshaped_arr = np.reshape(squeezed_arr,newshape=(120,))


In [ ]:
reshaped_arr.shape

(120,)

In [ ]:
arr = np.random.randint(low=0,hogh=20,size=10)

In [ ]:
arr

array([0.25, 0.5 , 1.  , 2.  , 4.  , 8.  ])

padding = it is used to add values on the basis of applications. now I have used padding for 1d-array.

In [ ]:
padded_arr=np.pad(arr,pad_width=(0,5),mode='constant',constant_values=0)

In [ ]:
padded_arr

array([0.25, 0.5 , 1.  , 2.  , 4.  , 8.  , 0.  , 0.  , 0.  , 0.  , 0.  ])

In [ ]:
padded_arr1 = np.pad(arr,pad_width=(5,0),mode='edge')

In [ ]:
padded_arr1

array([0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.5 , 1.  , 2.  , 4.  , 8.  ])

In [ ]:
padded_arr = np.pad(arr,pad_width=(2,3),mode='linear_ramp',end_values=(0.05,12))

In [ ]:
padded_arr

array([ 0.05      ,  0.15      ,  0.25      ,  0.5       ,  1.        ,
        2.        ,  4.        ,  8.        ,  9.33333333, 10.66666667,
       12.        ])

In [ ]:
padded_arr = np.pad(arr,pad_width=(3,2),mode='mean')

In [ ]:
padded_arr

array([2.625, 2.625, 2.625, 0.25 , 0.5  , 1.   , 2.   , 4.   , 8.   ,
       2.625, 2.625])

In [ ]:
padded_arr = np.pad(arr,pad_width=(2,3),mode='reflect')

In [ ]:
padded_arr

array([1.  , 0.5 , 0.25, 0.5 , 1.  , 2.  , 4.  , 8.  , 4.  , 2.  , 1.  ])

In [ ]:
twod_arr = np.random.randint(low = 0 , high = 20 , size= (2,3))

In [ ]:
twod_arr

array([[ 0,  3, 19],
       [19,  1, 18]])

In [ ]:
padded_2d_arr = np.pad(twod_arr, pad_width = ((2,0),(0,0)),mode = 'maximum')

In [ ]:
padded_2d_arr

array([[19,  3, 19],
       [19,  3, 19],
       [ 0,  3, 19],
       [19,  1, 18]])

In [ ]:
padded_2d_arr = np.pad(twod_arr, pad_width = ((2,0),(3,0)),mode = 'maximum')

In [ ]:
padded_2d_arr

array([[19, 19, 19, 19,  3, 19],
       [19, 19, 19, 19,  3, 19],
       [19, 19, 19,  0,  3, 19],
       [19, 19, 19, 19,  1, 18]])

In [ ]:
three_d_arr = np.random.randint(low = 0 , high = 30, size = (3,4,5))

In [ ]:
three_d_arr

array([[[23, 15,  8, 16, 17],
        [26,  2, 15, 28, 15],
        [24,  8,  2, 12, 20],
        [27, 10, 20,  3, 17]],

       [[23, 10, 21, 16,  0],
        [15, 14,  1, 29, 18],
        [10, 17,  0, 29, 25],
        [24, 19, 15,  8, 23]],

       [[14, 25, 21,  2,  3],
        [22, 25, 15,  6, 10],
        [26, 16,  3, 17, 13],
        [14, 13, 28, 23,  6]]])

In [ ]:
padded_3d_arr = np.pad(three_d_arr,pad_width=((3,0),(4,0),(0,5)),mode ='symmetric')

In [ ]:
padded_3d_arr

array([[[14, 13, 28, 23,  6,  6, 23, 28, 13, 14],
        [26, 16,  3, 17, 13, 13, 17,  3, 16, 26],
        [22, 25, 15,  6, 10, 10,  6, 15, 25, 22],
        [14, 25, 21,  2,  3,  3,  2, 21, 25, 14],
        [14, 25, 21,  2,  3,  3,  2, 21, 25, 14],
        [22, 25, 15,  6, 10, 10,  6, 15, 25, 22],
        [26, 16,  3, 17, 13, 13, 17,  3, 16, 26],
        [14, 13, 28, 23,  6,  6, 23, 28, 13, 14]],

       [[24, 19, 15,  8, 23, 23,  8, 15, 19, 24],
        [10, 17,  0, 29, 25, 25, 29,  0, 17, 10],
        [15, 14,  1, 29, 18, 18, 29,  1, 14, 15],
        [23, 10, 21, 16,  0,  0, 16, 21, 10, 23],
        [23, 10, 21, 16,  0,  0, 16, 21, 10, 23],
        [15, 14,  1, 29, 18, 18, 29,  1, 14, 15],
        [10, 17,  0, 29, 25, 25, 29,  0, 17, 10],
        [24, 19, 15,  8, 23, 23,  8, 15, 19, 24]],

       [[27, 10, 20,  3, 17, 17,  3, 20, 10, 27],
        [24,  8,  2, 12, 20, 20, 12,  2,  8, 24],
        [26,  2, 15, 28, 15, 15, 28, 15,  2, 26],
        [23, 15,  8, 16, 17, 17, 16,  8, 15, 2

In [ ]:
padded_3d_arr = np.pad(three_d_arr,pad_width=((3,0),(4,0),(0,5)),mode ='wrap')

In [ ]:
padded_3d_arr

array([[[23, 15,  8, 16, 17, 23, 15,  8, 16, 17],
        [26,  2, 15, 28, 15, 26,  2, 15, 28, 15],
        [24,  8,  2, 12, 20, 24,  8,  2, 12, 20],
        [27, 10, 20,  3, 17, 27, 10, 20,  3, 17],
        [23, 15,  8, 16, 17, 23, 15,  8, 16, 17],
        [26,  2, 15, 28, 15, 26,  2, 15, 28, 15],
        [24,  8,  2, 12, 20, 24,  8,  2, 12, 20],
        [27, 10, 20,  3, 17, 27, 10, 20,  3, 17]],

       [[23, 10, 21, 16,  0, 23, 10, 21, 16,  0],
        [15, 14,  1, 29, 18, 15, 14,  1, 29, 18],
        [10, 17,  0, 29, 25, 10, 17,  0, 29, 25],
        [24, 19, 15,  8, 23, 24, 19, 15,  8, 23],
        [23, 10, 21, 16,  0, 23, 10, 21, 16,  0],
        [15, 14,  1, 29, 18, 15, 14,  1, 29, 18],
        [10, 17,  0, 29, 25, 10, 17,  0, 29, 25],
        [24, 19, 15,  8, 23, 24, 19, 15,  8, 23]],

       [[14, 25, 21,  2,  3, 14, 25, 21,  2,  3],
        [22, 25, 15,  6, 10, 22, 25, 15,  6, 10],
        [26, 16,  3, 17, 13, 26, 16,  3, 17, 13],
        [14, 13, 28, 23,  6, 14, 13, 28, 23,  

In [3]:
arr = np.random.randint(low = 5 , high = 25 , size = (4,7))

In [173]:
arr

array([[15, 17, 14, 14, 15, 21, 20],
       [20, 17, 11, 15, 12, 12,  5],
       [ 9, 17,  9, 20, 17, 20, 15],
       [21,  9, 22, 16, 12, 17, 19]])

In [174]:
max_element = np.max(arr)

In [175]:
max_element

np.int64(22)

In [176]:
max_elements = np.max(arr,axis =1)

In [177]:
max_elements


array([21, 20, 20, 22])

In [178]:
max_elements = np.max(arr,axis = 0)

In [179]:
max_elements 

array([21, 17, 22, 20, 17, 21, 20])

In [180]:
max_idx = np.argmax(arr)

In [181]:
raveled_arr = np.ravel(arr)

In [182]:
raveled_arr

array([15, 17, 14, 14, 15, 21, 20, 20, 17, 11, 15, 12, 12,  5,  9, 17,  9,
       20, 17, 20, 15, 21,  9, 22, 16, 12, 17, 19])

In [183]:
max_idx

np.int64(23)

In [184]:
max_idx

np.int64(23)

np.argmax = this function is used to determine the index of the maximum element in a NumPy array

In [185]:
max_idx = np.argmax(arr,axis = 1)

In [186]:
max_idx

array([5, 0, 3, 2])

In [187]:
max_idx = np.argmax(arr,axis = 0)

In [188]:
max_idx

array([3, 0, 3, 2, 2, 0, 0])

In [189]:
arr

array([[15, 17, 14, 14, 15, 21, 20],
       [20, 17, 11, 15, 12, 12,  5],
       [ 9, 17,  9, 20, 17, 20, 15],
       [21,  9, 22, 16, 12, 17, 19]])

In [190]:
bmask = arr > 10

In [191]:
bmask

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True, False],
       [False,  True, False,  True,  True,  True,  True],
       [ True, False,  True,  True,  True,  True,  True]])

concept of creating boolean mask based on conditions as well as np.argwhere function

In [192]:
satisfied_elements = np.argwhere(bmask)

In [193]:
satisfied_elements

array([[0, 0],
       [0, 1],
       [0, 2],
       [0, 3],
       [0, 4],
       [0, 5],
       [0, 6],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 3],
       [1, 4],
       [1, 5],
       [2, 1],
       [2, 3],
       [2, 4],
       [2, 5],
       [2, 6],
       [3, 0],
       [3, 2],
       [3, 3],
       [3, 4],
       [3, 5],
       [3, 6]])

In [194]:
x_cord = np.linspace(start = 0,stop = 2 , endpoint=True,num =3)
y_cord = np.linspace(start = 0,stop = 4, endpoint=True,num =5)

In [196]:
x_cord

array([0., 1., 2.])

In [197]:
y_cord

array([0., 1., 2., 3., 4.])

In [198]:
y_cord_arr,x_cord_arr = np.meshgrid(y_cord,x_cord)

In [199]:
x_cord_arr

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.]])

In [200]:
y_cord_arr

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [201]:
x_cord = np.linspace(start = 0,stop = 2 , endpoint=True,num =5)
y_cord = np.linspace(start = 0,stop = 4, endpoint=True,num =9)

In [202]:
x_cord

array([0. , 0.5, 1. , 1.5, 2. ])

In [203]:
y_cord

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

meshgrid = it is used to give a grid of co-ordinates

In [205]:
y_cord_arr,x_cord_arr = np.meshgrid(y_cord,x_cord)

In [206]:
x_cord_arr

array([[0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. , 1. ],
       [1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5],
       [2. , 2. , 2. , 2. , 2. , 2. , 2. , 2. , 2. ]])

In [207]:
y_cord_arr

array([[0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ],
       [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ],
       [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ],
       [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ],
       [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ]])

np.cov function to compute the covariance matrix from some data stored as NumPy array

In [5]:
arr = np.random.randint(low = 5 , high = 25 , size = (4,5))

In [ ]:
arr

array([[24,  6,  6,  9, 10],
       [18, 16, 16,  6, 24],
       [ 9, 13, 13, 17, 21],
       [21, 14, 15, 10, 13]])

In [7]:
cov_matrix = np.cov(arr,rowvar=False)

In [8]:
cov_matrix

array([[ 42.        , -13.        , -12.        , -23.        ,
        -30.        ],
       [-13.        ,  18.91666667,  19.5       ,  -1.16666667,
         22.        ],
       [-12.        ,  19.5       ,  20.33333333,  -1.33333333,
         20.66666667],
       [-23.        ,  -1.16666667,  -1.33333333,  21.66666667,
          2.33333333],
       [-30.        ,  22.        ,  20.66666667,   2.33333333,
         43.33333333]])

 np.dot function to compute the dot product between two 1D NumPy arrays (vectors)

In [9]:
left_vec = np.random.randint(low = 4 , high = 21 , size = (4,))
right_vec = np.random.randint(low = 4 , high = 21 , size = (4,))

In [11]:
left_vec

array([ 4, 11,  9,  8])

In [12]:
right_vec

array([18, 16, 19,  7])

In [10]:
scalar = np.dot(left_vec,right_vec)

In [13]:
scalar

np.int64(475)

Concept of matrix multiplication using matmul function .

In [ ]:
left_vec = np.random.randint(low = 5 , high = 25 , size= (5,7))
right_vec = np.random.randint(low = 5 , high = 25 , size= (7,3))

In [15]:
mat_prod = np.matmul(left_vec,right_vec)

In [16]:
mat_prod

array([[ 990, 1007, 1098],
       [1366, 1442, 1537],
       [1540, 1823, 1762],
       [1386, 1627, 1579],
       [1297, 1492, 1362]])

In [19]:
left_vec = np.random.randint(low = 5 , high = 52 , size= (5,7,4))
right_vec = np.random.randint(low = 5 , high = 52 , size= (4,3))

In [20]:
mat_prod = np.matmul(left_vec , right_vec)

In [21]:
mat_prod

array([[[3507, 5725, 2384],
        [2518, 4942, 2358],
        [1367, 2830, 1569],
        [2833, 4012, 1629],
        [1250, 2577, 1265],
        [3083, 5079, 2156],
        [1907, 3712, 1725]],

       [[2374, 3235, 1217],
        [1222, 2114, 1028],
        [1979, 2955, 1226],
        [3253, 5685, 2510],
        [2865, 4466, 1713],
        [3069, 5412, 2385],
        [2490, 4596, 2160]],

       [[2870, 4540, 1722],
        [2865, 3537, 1108],
        [2712, 3614, 1322],
        [2924, 3960, 1494],
        [ 977, 2183, 1066],
        [1703, 2476,  921],
        [2020, 3643, 1683]],

       [[2503, 3642, 1397],
        [2908, 4361, 1555],
        [2015, 2848, 1141],
        [1350, 2439, 1193],
        [2154, 3670, 1672],
        [2458, 4121, 1897],
        [2988, 4830, 2124]],

       [[1387, 3311, 1930],
        [1548, 3471, 1719],
        [1282, 2652, 1270],
        [1422, 2373, 1153],
        [3061, 5208, 2171],
        [1886, 3480, 1718],
        [3086, 4862, 1976]]])