In [145]:
import numpy as np 

In [146]:
l = [1,2,3,6,5,4,8,7,9]
arr = np.array(l)
print(arr)

[1 2 3 6 5 4 8 7 9]


In [147]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [148]:
l2 = [[[1,2,3,],[4,5,6,],[7,8,9],[10,11,12]]]

In [149]:
l2

[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]]

In [150]:
np.shape(l2)

(1, 4, 3)

In [151]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [152]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [153]:
arr.shape

(9,)

In [154]:
l2 = np.reshape(l2,(3,2,2))

In [155]:
np.shape(l2)

(3, 2, 2)

In [156]:
print(l2)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [157]:
l2 [0,1,0]

np.int64(3)

In [158]:
l2 [0,0,0]

np.int64(1)

In [159]:
l2 [2,1,:]

array([11, 12])

In [160]:
l5 = [1,2,3,4,5,6,7,8,9,10]

In [161]:
l5

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [162]:
l5 * 2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [163]:
l5 = np.array(l5)

In [164]:
l5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [165]:
l5.shape

(10,)

In [166]:
l5 = l5.reshape(5,2)

In [167]:
l5

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [168]:
l6 = [1,2,3,4,5,6,7,8,9,10]

In [169]:
arr=np.array(l6)

In [170]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [171]:
arr* 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [172]:
arr + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [173]:
arr - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [174]:
arr.shape


(10,)

In [175]:
arr = arr.reshape(2,5)

In [176]:
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [177]:
l7 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [178]:
l7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [179]:
l7.shape

(12,)

In [180]:
l8 = np.array([1,8,4,5,6,9,7,1,2,20,11,13])

In [181]:
l8

array([ 1,  8,  4,  5,  6,  9,  7,  1,  2, 20, 11, 13])

In [182]:
l8.shape

(12,)

In [183]:
l8 = l8.reshape(1,12)

In [184]:
l8.shape

(1, 12)

In [185]:
l9 = l8 + l7

In [186]:
l9 

array([[ 2, 10,  7,  9, 11, 15, 14,  9, 11, 30, 22, 25]])

In [187]:
l9.shape

(1, 12)

In [188]:
l10 = np.array([1,5,8,7,4,6,9,2,3,6,5,4,7,8])

In [189]:
l10

array([1, 5, 8, 7, 4, 6, 9, 2, 3, 6, 5, 4, 7, 8])

In [190]:
l10.shape

(14,)

In [191]:
l10 = l10.reshape(14,1)

In [192]:
l11 = l10 + l7

In [193]:
l11

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [194]:
l12 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24])

In [195]:
l12 = l12.reshape(2,12)

In [196]:
l13 = l12 + l7

In [197]:
l13.shape

(2, 12)

In [198]:
l12 = l12.reshape(2,12)

In [199]:
l13 = l7 + l12

to add two matrix(array) we have to make their y-axis or columns of same value.

In [200]:
l13

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24],
       [14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36]])

In [201]:
l7.shape

(12,)

In [202]:
l12.shape

(2, 12)

In [203]:
l9.shape

(1, 12)

In [204]:
arr1=l9+l12

In [205]:
arr1

array([[ 3, 12, 10, 13, 16, 21, 21, 17, 20, 40, 33, 37],
       [15, 24, 22, 25, 28, 33, 33, 29, 32, 52, 45, 49]])

In [206]:
arr3=l9.reshape(1,12)

In [207]:
arr3

array([[ 2, 10,  7,  9, 11, 15, 14,  9, 11, 30, 22, 25]])

In [208]:
arr3.shape


(1, 12)

In [209]:
arr2 = l9+l7

In [210]:
arr2

array([[ 3, 12, 10, 13, 16, 21, 21, 17, 20, 40, 33, 37]])

In [211]:
l7.shape

(12,)

In [212]:
arr4=l7+l9

In [213]:
arr4

array([[ 3, 12, 10, 13, 16, 21, 21, 17, 20, 40, 33, 37]])

In [214]:
arr5 = arr4+arr3

In [215]:
arr5

array([[ 5, 22, 17, 22, 27, 36, 35, 26, 31, 70, 55, 62]])

In [216]:
arr6=l9.reshape(2,6)    

In [217]:
arr7=l7.reshape(2,6)

In [218]:
arr8=arr6+arr7

In [219]:
arr8

array([[ 3, 12, 10, 13, 16, 21],
       [21, 17, 20, 40, 33, 37]])

zeros = it is used to make an array of values = 0

In [220]:
arr9 = np.zeros((2,10))

In [221]:
arr = np.ones((4,8),dtype=int)

In [222]:
arr

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [223]:
arr = arr.reshape(8,1,1,1,1,1,1,4)

In [224]:
arr

array([[[[[[[[1, 1, 1, 1]]]]]]],






       [[[[[[[1, 1, 1, 1]]]]]]],






       [[[[[[[1, 1, 1, 1]]]]]]],






       [[[[[[[1, 1, 1, 1]]]]]]],






       [[[[[[[1, 1, 1, 1]]]]]]],






       [[[[[[[1, 1, 1, 1]]]]]]],






       [[[[[[[1, 1, 1, 1]]]]]]],






       [[[[[[[1, 1, 1, 1]]]]]]]])

In [225]:
arr9

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [226]:
arr9=np.zeros((5,10),dtype=int)


In [227]:
arr9

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

ones = it is used to generate an array of ony unit digits .

In [228]:
arr = np.ones((9,15))

In [229]:
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

empty = it is used to get an array of randomly generated values or garbage values .

In [230]:
arr = np.empty((4,6))

In [231]:
arr

array([[3.75566827e-316, 0.00000000e+000, 3.45845952e-323,
        4.44659081e-323, 5.43472210e-323, 7.41098469e-323],
       [6.91691904e-323, 4.44659081e-323, 5.43472210e-323,
        1.48219694e-322, 1.08694442e-322, 1.23516411e-322],
       [9.88131292e-324, 4.94065646e-323, 3.45845952e-323,
        4.44659081e-323, 5.43472210e-323, 7.41098469e-323],
       [6.91691904e-323, 4.44659081e-323, 5.43472210e-323,
        1.48219694e-322, 1.08694442e-322, 1.23516411e-322]])

In [232]:
arr = np.empty((4,6),dtype=int)

In [233]:
arr 

array([[76015572,        0,        7,        9,       11,       15],
       [      14,        9,       11,       30,       22,       25],
       [       2,       10,        7,        9,       11,       15],
       [      14,        9,       11,       30,       22,       25]])

arange = it is used to get an array of desired staring point & ending point with how much differnce we want in the two values .

In [234]:
arr = np.arange(0,20,2.5,dtype=np.float64)

In [235]:
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5])

linspace = it is used to make an array of desired staring point & ending point with how much values we want then the funtion will generate the gap itself according to the values 

In [236]:
arr = np.linspace(0,10,20)

In [237]:
arr

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [238]:
arr = np.random.binomial(n=6,p=0.6,size=(2,5))

In [239]:
arr

array([[5, 4, 4, 4, 4],
       [5, 6, 2, 3, 4]])

In [240]:
arr = np.random.binomial(n=1,p=0.5,size=(2,5))

In [241]:
arr

array([[1, 0, 0, 1, 1],
       [0, 0, 0, 0, 1]])

In [242]:
arr = np.random.multivariate_normal(mean=[1,1,1,1],cov=[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]],size=10)

In [243]:
arr

array([[ 0.33079611, -0.52490579,  1.73959397,  1.34795606],
       [ 0.00956689,  0.87736023,  0.72321568,  2.58081569],
       [ 0.7154807 ,  0.16187443,  0.89644378,  0.66574648],
       [ 1.41948821,  1.87056482,  3.12069563,  0.49603863],
       [-0.72142241,  2.47388838, -0.57175104,  0.93481232],
       [ 0.12475361,  1.70424738, -0.91577756,  1.61424943],
       [ 1.23070522,  0.43250557,  1.06626061,  1.75678717],
       [ 0.68586254,  1.40161834,  0.28000272,  0.62196934],
       [ 1.28656263,  1.7162222 ,  0.29525891,  0.33291133],
       [ 2.58975372,  2.17397727,  1.90501262,  2.18951036]])

In [244]:
arr = np.random.multivariate_normal(mean=[1,2,3,4],cov=[[1,0,0,0],[0,2,0,0],[0,0,3,0],[0,0,0,4]],size=10)

In [245]:
arr

array([[ 0.90585469,  4.04502015,  2.95617976,  6.21440386],
       [-0.08040807,  2.04079088,  1.58467836,  6.73057656],
       [-1.03168761,  3.59343207,  1.75893776,  2.57399822],
       [ 0.85628131,  2.03445028,  6.88341691,  3.36956382],
       [ 1.48707283,  0.21502007,  1.68492668,  3.03869795],
       [ 1.13271131,  3.01426653,  4.16237343,  6.37515525],
       [ 1.68551851,  3.06155716,  2.50255971,  7.0540565 ],
       [ 2.48860331,  1.32703435,  2.4458944 ,  4.50809454],
       [ 1.70736191,  6.13916214,  1.77017155,  5.09649682],
       [ 1.31094104,  3.53588515,  0.70576344,  9.70285776]])

In [246]:
arr = np.random.normal(loc=5,scale=1,size=(2,10))

In [247]:
arr

array([[5.68003735, 5.60140644, 5.12403667, 5.60617111, 4.3453629 ,
        5.59803629, 4.46001915, 4.04508126, 6.15845857, 5.59121081],
       [5.74061626, 5.87655638, 4.0910717 , 2.11039201, 5.49631909,
        4.87235093, 4.16503408, 4.89041606, 6.1216173 , 3.79038531]])

In [248]:
arr_mean=np.mean(arr)

In [249]:
arr_mean

np.float64(4.968228984292973)

In [250]:
arr = np.random.rand(10,10)

In [251]:
arr

array([[0.9724697 , 0.07864573, 0.2096751 , 0.20983576, 0.18005308,
        0.67094101, 0.60625431, 0.86648857, 0.68235647, 0.18619978],
       [0.83004214, 0.26201631, 0.32119523, 0.50926548, 0.41107913,
        0.07529363, 0.59418386, 0.71800226, 0.74198156, 0.93445257],
       [0.31889903, 0.7896723 , 0.71476661, 0.67235002, 0.64504682,
        0.88150628, 0.62796239, 0.96514271, 0.7986775 , 0.34990319],
       [0.54018604, 0.98786655, 0.72827336, 0.86216464, 0.48296277,
        0.38465221, 0.65143437, 0.95480397, 0.61899474, 0.96619468],
       [0.69457674, 0.98363441, 0.16144401, 0.74215503, 0.19462754,
        0.02697163, 0.66697487, 0.57506178, 0.35610193, 0.63047661],
       [0.93426984, 0.6384094 , 0.76285615, 0.25060572, 0.72167212,
        0.00986882, 0.89863531, 0.47595349, 0.83927818, 0.81655356],
       [0.12954605, 0.3755435 , 0.28206313, 0.43966517, 0.20186236,
        0.41366352, 0.06202255, 0.19153677, 0.25985942, 0.85908962],
       [0.59550683, 0.99867222, 0.5451249

In [252]:
arr = np.random.randint(low=10,high=25,size= (2,20))

In [253]:
arr

array([[20, 18, 23, 23, 16, 20, 11, 18, 23, 20, 18, 12, 19, 18, 19, 22,
        24, 16, 24, 11],
       [17, 15, 24, 16, 17, 12, 24, 12, 17, 16, 10, 11, 18, 23, 11, 22,
        22, 15, 16, 10]])

In [254]:
arr = np.random.randn(5,10)

In [255]:
arr

array([[ 0.12101027,  0.62408723,  0.92192534,  0.81702612, -0.51386473,
        -0.54159006,  0.12358817,  0.89340638,  0.57153235,  0.51838558],
       [-0.0207982 , -0.51632033,  0.83466865,  0.02237624, -1.2530866 ,
         0.13968647, -1.14113773,  0.51530736, -0.17029565,  0.19331829],
       [ 2.23167922, -0.9385532 ,  0.39309702,  1.94083427,  0.7300955 ,
         0.08167353,  1.9022399 , -0.05744343, -1.39036033, -0.83638073],
       [ 1.36513408, -2.31522722,  2.14915729, -0.56982436,  2.5774243 ,
         1.14846771,  0.22434702, -0.7879137 ,  0.11802947,  1.15686761],
       [ 1.49415335,  0.20052857,  0.42196957, -0.13340665,  0.7927745 ,
         1.44531398,  0.30074276, -0.31010613,  0.26012779, -0.27752136]])

In [256]:
c = []

In [257]:
arr = np.array(c)

In [258]:
arr

array([], dtype=float64)

In [259]:
arr = np.zeros((0,0))

In [260]:
arr

array([], shape=(0, 0), dtype=float64)

In [261]:
arr = np.array((x:=[2,4,5,1,7,8,6,9,6,4]))

In [262]:
arr

array([2, 4, 5, 1, 7, 8, 6, 9, 6, 4])

eye - it create a numpy array having ones at diagonals.

In [263]:
arr = np.eye(3)

In [264]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [265]:
arr = np.eye(5,6)

In [266]:
arr

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [267]:
arr = np.eye(6,4)

In [268]:
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

logspace - it is used to generate a set of number whose ratio is same not difference in log scale.

In [269]:
arr = np.logspace(start=-2,stop=3,base=10,num=5)

In [270]:
arr

array([1.00000000e-02, 1.77827941e-01, 3.16227766e+00, 5.62341325e+01,
       1.00000000e+03])

In [271]:
arr = np.logspace(start=-2,stop=3,base=2,num=6)

In [272]:
arr

array([0.25, 0.5 , 1.  , 2.  , 4.  , 8.  ])

concatenate = it is used to combine two numpy arrays in different axises and can concatenate multiple numpy arrays .

In [273]:
left_arr = np.random.binomial(n=7,p=0.4,size=(2,6))
right_arr = np.random.binomial(n=10,p=0.6,size=(2,6))

In [274]:
row_wise_concat_arr = np.concatenate((left_arr,right_arr),axis=0)
col_wise_concat_arr = np.concatenate((left_arr,right_arr),axis=1)


In [275]:
row_wise_concat_arr

array([[5, 5, 3, 2, 3, 2],
       [1, 3, 4, 4, 4, 4],
       [5, 6, 5, 8, 5, 6],
       [6, 8, 7, 3, 7, 5]])

In [276]:
col_wise_concat_arr

array([[5, 5, 3, 2, 3, 2, 5, 6, 5, 8, 5, 6],
       [1, 3, 4, 4, 4, 4, 6, 8, 7, 3, 7, 5]])

delete = it deletes the rows or columns or depths of which axises are given.(in this condition)

In [277]:
col_wise_concat_arr = np.delete(col_wise_concat_arr,[1,3],axis=1)

In [278]:
col_wise_concat_arr

array([[5, 3, 3, 2, 5, 6, 5, 8, 5, 6],
       [1, 4, 4, 4, 6, 8, 7, 3, 7, 5]])

In [279]:
row_wise_concat_arr = np.delete(row_wise_concat_arr,[1,3],axis=0)

In [280]:
row_wise_concat_arr

array([[5, 5, 3, 2, 3, 2],
       [5, 6, 5, 8, 5, 6]])

Done -> Concept of boolean masking in numpy arrays . 

In [281]:
bmask = np.ones((col_wise_concat_arr.shape[1],),dtype=bool)

In [282]:
bmask

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [283]:
bmask[1]=False
bmask[5]=False

In [284]:
bmask

array([ True, False,  True,  True,  True, False,  True,  True,  True,
        True])

In [285]:
col_wise_concat_arr[:,bmask]

array([[5, 3, 2, 5, 5, 8, 5, 6],
       [1, 4, 4, 6, 7, 3, 7, 5]])

In [286]:
bmask1=np.ones((row_wise_concat_arr.shape[0],),dtype=bool)

In [287]:
bmask1

array([ True,  True])

In [288]:
bmask1[1]=False
bmask1[3]=False

IndexError: index 3 is out of bounds for axis 0 with size 2

In [ ]:
bmask1

array([ True, False,  True, False])

In [ ]:
row_wise_concat_arr[bmask1,:]

array([[1, 4, 1, 3, 3, 2],
       [4, 9, 4, 7, 7, 5]])

In [ ]:
arr8=arr8.reshape(2,6)

In [ ]:
arr8

array([[ 3, 12, 10, 13, 16, 21],
       [21, 17, 20, 40, 33, 37]])

In [ ]:
arr8 = np.expand_dims(arr8,axis=1)

In [ ]:
arr8.shape

(2, 1, 6)

In [ ]:
arr8

array([[[ 3, 12, 10, 13, 16, 21]],

       [[21, 17, 20, 40, 33, 37]]])

In [ ]:
arr = np.random.randint(low=0,high=20,size=(1,2,3,4,5))

In [ ]:
arr

array([[[[[ 2,  8,  5,  2, 13],
          [14, 16,  9, 13, 19],
          [ 0, 16, 17,  1,  3],
          [11, 17,  2, 19, 18]],

         [[14,  7,  2,  5,  6],
          [ 0,  3, 12, 12, 14],
          [19, 11,  8,  2, 17],
          [15, 16,  1, 15, 19]],

         [[ 7,  6,  3,  7, 15],
          [ 4,  2,  3, 17,  7],
          [ 6,  0, 10,  2,  7],
          [18,  8,  4,  2, 13]]],


        [[[10,  4,  6, 14, 12],
          [17,  7,  0, 12, 18],
          [11,  2,  6, 11,  1],
          [15,  7,  2,  3, 18]],

         [[ 7, 19, 17,  2, 17],
          [16,  8, 16, 13,  4],
          [ 2,  5, 14, 19,  0],
          [ 4,  3,  5,  1,  5]],

         [[ 4, 19, 14,  7,  8],
          [16,  9,  8, 17, 14],
          [16,  5, 14,  7, 14],
          [ 5, 17,  1,  2,  6]]]]])

In [ ]:
arr.shape

(1, 2, 3, 4, 5)

Inserting new axes into a NumPy array, concept of ellipsis as well as it's notation.

In [ ]:
arr = arr[:,:,np.newaxis,...]

In [ ]:
arr.shape

(1, 2, 1, 3, 4, 5)

squeeze = it is used to squeeze the size of an array by removing all 1 .

In [ ]:
squeezed_arr=np.squeeze(arr)

In [ ]:
squeezed_arr.shape

(2, 3, 4, 5)

ravel = it is used to make a single dimnesion array with all the elements .

In [ ]:
flattened_arr = np.ravel(squeezed_arr)

In [ ]:
flattened_arr.shape

(120,)

reshape = it is used to reshape an array in different dimensions but the no. of elements should be same.

In [ ]:
reshaped_arr = np.reshape(squeezed_arr,newshape=(3,5,4,1,2))

/tmp/ipykernel_2365/1100543301.py:1: DeprecationWarning: `newshape` keyword argument is deprecated, use `shape=...` or pass shape positionally instead. (deprecated in NumPy 2.1)
  reshaped_arr = np.reshape(squeezed_arr,newshape=(3,5,4,1,2))


In [ ]:
reshaped_arr.shape

(3, 5, 4, 1, 2)

In [ ]:
reshaped_arr = np.reshape(squeezed_arr,newshape=(15,1,8))

/tmp/ipykernel_2365/1744322687.py:1: DeprecationWarning: `newshape` keyword argument is deprecated, use `shape=...` or pass shape positionally instead. (deprecated in NumPy 2.1)
  reshaped_arr = np.reshape(squeezed_arr,newshape=(15,1,8))


In [ ]:
reshaped_arr.shape

(15, 1, 8)

In [ ]:
reshaped_arr = np.reshape(squeezed_arr,newshape=(120,))

/tmp/ipykernel_2365/4254991431.py:1: DeprecationWarning: `newshape` keyword argument is deprecated, use `shape=...` or pass shape positionally instead. (deprecated in NumPy 2.1)
  reshaped_arr = np.reshape(squeezed_arr,newshape=(120,))


In [ ]:
reshaped_arr.shape

(120,)

In [ ]:
arr = np.random.randint(low=0,hogh=20,size=10)

In [ ]:
arr

array([0.25, 0.5 , 1.  , 2.  , 4.  , 8.  ])

padding = it is used to add values on the basis of applications. now I have used padding for 1d-array.

In [ ]:
padded_arr=np.pad(arr,pad_width=(0,5),mode='constant',constant_values=0)

In [ ]:
padded_arr

array([0.25, 0.5 , 1.  , 2.  , 4.  , 8.  , 0.  , 0.  , 0.  , 0.  , 0.  ])

In [ ]:
padded_arr1 = np.pad(arr,pad_width=(5,0),mode='edge')

In [ ]:
padded_arr1

array([0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.5 , 1.  , 2.  , 4.  , 8.  ])

In [ ]:
padded_arr = np.pad(arr,pad_width=(2,3),mode='linear_ramp',end_values=(0.05,12))

In [ ]:
padded_arr

array([ 0.05      ,  0.15      ,  0.25      ,  0.5       ,  1.        ,
        2.        ,  4.        ,  8.        ,  9.33333333, 10.66666667,
       12.        ])

In [ ]:
padded_arr = np.pad(arr,pad_width=(3,2),mode='mean')

In [ ]:
padded_arr

array([2.625, 2.625, 2.625, 0.25 , 0.5  , 1.   , 2.   , 4.   , 8.   ,
       2.625, 2.625])

In [ ]:
padded_arr = np.pad(arr,pad_width=(2,3),mode='reflect')

In [ ]:
padded_arr

array([1.  , 0.5 , 0.25, 0.5 , 1.  , 2.  , 4.  , 8.  , 4.  , 2.  , 1.  ])

In [291]:
twod_arr = np.random.randint(low = 0 , high = 20 , size= (2,3))

In [292]:
twod_arr

array([[ 0,  3, 19],
       [19,  1, 18]])

In [294]:
padded_2d_arr = np.pad(twod_arr, pad_width = ((2,0),(0,0)),mode = 'maximum')

In [295]:
padded_2d_arr

array([[19,  3, 19],
       [19,  3, 19],
       [ 0,  3, 19],
       [19,  1, 18]])

In [296]:
padded_2d_arr = np.pad(twod_arr, pad_width = ((2,0),(3,0)),mode = 'maximum')

In [297]:
padded_2d_arr

array([[19, 19, 19, 19,  3, 19],
       [19, 19, 19, 19,  3, 19],
       [19, 19, 19,  0,  3, 19],
       [19, 19, 19, 19,  1, 18]])