In [2]:
import numpy as np 

In [3]:
l = [1,2,3,6,5,4,8,7,9]
arr = np.array(l)
print(arr)

[1 2 3 6 5 4 8 7 9]


In [4]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [5]:
l2 = [[[1,2,3,],[4,5,6,],[7,8,9],[10,11,12]]]

In [6]:
l2

[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]]

In [7]:
np.shape(l2)

(1, 4, 3)

In [8]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [9]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [10]:
arr.shape

(9,)

In [11]:
l2 = np.reshape(l2,(3,2,2))

In [12]:
np.shape(l2)

(3, 2, 2)

In [13]:
print(l2)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [14]:
l2 [0,1,0]

np.int64(3)

In [15]:
l2 [0,0,0]

np.int64(1)

In [16]:
l2 [2,1,:]

array([11, 12])

In [17]:
l5 = [1,2,3,4,5,6,7,8,9,10]

In [18]:
l5

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [19]:
l5 * 2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [20]:
l5 = np.array(l5)

In [21]:
l5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
l5.shape

(10,)

In [23]:
l5 = l5.reshape(5,2)

In [24]:
l5

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [25]:
l6 = [1,2,3,4,5,6,7,8,9,10]

In [26]:
arr=np.array(l6)

In [27]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr* 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [29]:
arr + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [30]:
arr - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [31]:
arr.shape


(10,)

In [32]:
arr = arr.reshape(2,5)

In [33]:
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [34]:
l7 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [35]:
l7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
l7.shape

(12,)

In [37]:
l8 = np.array([1,8,4,5,6,9,7,1,2,20,11,13])

In [38]:
l8

array([ 1,  8,  4,  5,  6,  9,  7,  1,  2, 20, 11, 13])

In [39]:
l8.shape

(12,)

In [40]:
l8 = l8.reshape(1,12)

In [41]:
l8.shape

(1, 12)

In [42]:
l9 = l8 + l7

In [43]:
l9 

array([[ 2, 10,  7,  9, 11, 15, 14,  9, 11, 30, 22, 25]])

In [44]:
l9.shape

(1, 12)

In [45]:
l10 = np.array([1,5,8,7,4,6,9,2,3,6,5,4,7,8])

In [46]:
l10

array([1, 5, 8, 7, 4, 6, 9, 2, 3, 6, 5, 4, 7, 8])

In [47]:
l10.shape

(14,)

In [48]:
l10 = l10.reshape(14,1)

In [49]:
l11 = l10 + l7

In [50]:
l11

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [51]:
l12 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24])

In [52]:
l12 = l12.reshape(2,12)

In [53]:
l13 = l12 + l7

In [54]:
l13.shape

(2, 12)

In [55]:
l12 = l12.reshape(2,12)

In [56]:
l13 = l7 + l12

to add two matrix(array) we have to make their y-axis or columns of same value.

In [57]:
l13

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24],
       [14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36]])

In [58]:
l7.shape

(12,)

In [59]:
l12.shape

(2, 12)

In [60]:
l9.shape

(1, 12)

In [61]:
arr1=l9+l12

In [62]:
arr1

array([[ 3, 12, 10, 13, 16, 21, 21, 17, 20, 40, 33, 37],
       [15, 24, 22, 25, 28, 33, 33, 29, 32, 52, 45, 49]])

In [63]:
arr3=l9.reshape(1,12)

In [64]:
arr3

array([[ 2, 10,  7,  9, 11, 15, 14,  9, 11, 30, 22, 25]])

In [65]:
arr3.shape


(1, 12)

In [66]:
arr2 = l9+l7

In [67]:
arr2

array([[ 3, 12, 10, 13, 16, 21, 21, 17, 20, 40, 33, 37]])

In [68]:
l7.shape

(12,)

In [69]:
arr4=l7+l9

In [70]:
arr4

array([[ 3, 12, 10, 13, 16, 21, 21, 17, 20, 40, 33, 37]])

In [71]:
arr5 = arr4+arr3

In [72]:
arr5

array([[ 5, 22, 17, 22, 27, 36, 35, 26, 31, 70, 55, 62]])

In [ ]:
arr6=l9.reshape(2,6)    

In [74]:
arr7=l7.reshape(2,6)

In [75]:
arr8=arr6+arr7

In [76]:
arr8

array([[ 3, 12, 10, 13, 16, 21],
       [21, 17, 20, 40, 33, 37]])

zeros = it is used to make an array of values = 0

In [77]:
arr9 = np.zeros((2,10))

In [78]:
arr9

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [79]:
arr9=np.zeros((5,10),dtype=int)


In [80]:
arr9

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

ones = it is used to generate an array of ony unit digits .

In [81]:
arr = np.ones((9,15))

In [82]:
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

empty = it is used to get an array of randomly generated values or garbage values .

In [83]:
arr = np.empty((4,6))

In [84]:
arr

array([[2.55521323e-315, 0.00000000e+000, 3.45845952e-323,
        4.44659081e-323, 5.43472210e-323, 7.41098469e-323],
       [6.91691904e-323, 4.44659081e-323, 5.43472210e-323,
        1.48219694e-322, 1.08694442e-322, 1.23516411e-322],
       [9.88131292e-324, 4.94065646e-323, 3.45845952e-323,
        4.44659081e-323, 5.43472210e-323, 7.41098469e-323],
       [6.91691904e-323, 4.44659081e-323, 5.43472210e-323,
        1.48219694e-322, 1.08694442e-322, 1.23516411e-322]])

In [85]:
arr = np.empty((4,6),dtype=int)

In [86]:
arr 

array([[517180915,         0,         7,         9,        11,        15],
       [       14,         9,        11,        30,        22,        25],
       [        2,        10,         7,         9,        11,        15],
       [       14,         9,        11,        30,        22,        25]])

arange = it is used to get an array of desired staring point & ending point with how much differnce we want in the two values .

In [87]:
arr = np.arange(0,20,2.5,dtype=np.float64)

In [88]:
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5])

linspace = it is used to make an array of desired staring point & ending point with how much values we want then the funtion will generate the gap itself according to the values 

In [89]:
arr = np.linspace(0,10,20)

In [90]:
arr

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [91]:
arr = np.random.binomial(n=6,p=0.6,size=(2,5))

In [92]:
arr

array([[4, 3, 2, 3, 4],
       [4, 4, 2, 4, 2]])

In [93]:
arr = np.random.binomial(n=1,p=0.5,size=(2,5))

In [94]:
arr

array([[0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1]])

In [95]:
arr = np.random.multivariate_normal(mean=[1,1,1,1],cov=[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]],size=10)

In [96]:
arr

array([[ 1.32864916,  1.64365243,  2.88221751,  1.49163063],
       [ 0.50067221,  1.86559305,  1.53001402,  0.698852  ],
       [ 0.2853847 ,  1.66087426,  0.82628936,  2.10702296],
       [ 1.36598692,  1.49082643,  0.83582214, -0.60434456],
       [ 0.11924178,  0.50853836, -0.10775819,  1.85648743],
       [ 1.65922315,  1.35735707,  1.38800815,  1.03961096],
       [ 0.6106323 ,  0.11083444,  2.74566098,  1.59637545],
       [-0.10966742,  1.52035738,  1.63491342,  1.30754999],
       [ 1.91774087,  1.65877159,  1.75854625,  0.41881856],
       [-1.0586312 ,  2.27752753,  2.59028055,  1.40143307]])

In [97]:
arr = np.random.multivariate_normal(mean=[1,2,3,4],cov=[[1,0,0,0],[0,2,0,0],[0,0,3,0],[0,0,0,4]],size=10)

In [98]:
arr

array([[ 1.44289544,  3.12071904,  2.10413755,  1.75294535],
       [ 1.26391218,  0.99800855,  2.10066379,  5.83250408],
       [-0.09628159,  0.98953948,  1.27801948,  5.02212076],
       [ 0.65807476,  2.54212785,  7.64193243,  1.68358185],
       [ 1.69509377,  0.13865475,  2.97902532,  5.01204855],
       [ 1.41875231,  1.98223275,  0.99305267,  1.86216766],
       [ 1.48816232,  2.61397496,  2.83213199,  5.23709745],
       [-0.22920288,  4.1691187 ,  0.10471473,  7.18545679],
       [ 0.52531201,  1.30233187,  2.27488441,  7.7057126 ],
       [ 0.68039415,  3.73636095,  4.27879159,  3.69492866]])

In [99]:
arr = np.random.normal(loc=5,scale=1,size=(2,10))

In [100]:
arr

array([[6.05845029, 6.37609507, 4.48203441, 5.80377231, 4.03795838,
        4.86172893, 4.44741341, 4.98228387, 4.60791229, 4.79741949],
       [4.24815935, 4.78425899, 3.24339254, 4.26821068, 5.69352961,
        4.5802399 , 4.00194334, 4.26041545, 3.1828518 , 5.15290236]])

In [101]:
arr_mean=np.mean(arr)

In [102]:
arr_mean

np.float64(4.693548625553514)

In [103]:
arr = np.random.rand(10,10)

In [104]:
arr

array([[0.88184981, 0.93456682, 0.75964907, 0.08989477, 0.40412776,
        0.10649931, 0.28954179, 0.57240287, 0.52748456, 0.84067108],
       [0.88000487, 0.82034565, 0.11816829, 0.07525102, 0.07145987,
        0.25490418, 0.45299087, 0.29299535, 0.58015997, 0.94766856],
       [0.8618577 , 0.76495469, 0.76876252, 0.7864211 , 0.27075515,
        0.54405535, 0.75083465, 0.07121719, 0.15210525, 0.93919159],
       [0.14297749, 0.98741518, 0.02968387, 0.69242244, 0.25960241,
        0.65867908, 0.657163  , 0.8457805 , 0.8568849 , 0.89156118],
       [0.26367293, 0.50210626, 0.22325884, 0.7464441 , 0.08848824,
        0.70069396, 0.54622531, 0.55902415, 0.63857319, 0.68451217],
       [0.47184006, 0.72615815, 0.21960214, 0.00223356, 0.75593686,
        0.36322679, 0.02327277, 0.24663963, 0.45264235, 0.61936855],
       [0.62271793, 0.74960841, 0.78653131, 0.74555351, 0.1869463 ,
        0.02296436, 0.86973102, 0.93168828, 0.60245154, 0.52759722],
       [0.92445526, 0.91948506, 0.0467736

In [105]:
arr = np.random.randint(low=10,high=25,size= (2,20))

In [106]:
arr

array([[15, 23, 17, 21, 23, 12, 22, 23, 21, 17, 11, 23, 15, 10, 15, 14,
        11, 23, 11, 18],
       [15, 23, 15, 10, 20, 15, 15, 20, 10, 20, 19, 19, 12, 11, 10, 21,
        13, 14, 17, 19]])

In [107]:
arr = np.random.randn(5,10)

In [108]:
arr

array([[-1.22077599,  0.97645648,  0.66890361, -0.32847187, -2.35790963,
        -0.20469801,  0.21941892,  0.26490298,  0.9761975 , -1.08629716],
       [-0.15176179,  0.76354497, -0.0680805 , -0.90590197,  0.17948017,
         2.24221885,  1.67981804, -0.72609284, -0.21375037, -1.87764881],
       [ 1.91249403,  1.41252156,  1.47336195,  0.57660046,  0.31279655,
         0.26004494,  1.59403794, -0.79707256, -0.12313345,  2.09808085],
       [ 0.52906493,  0.2759684 , -1.14826837, -0.77255432, -1.01442883,
         0.99807463,  2.18235184, -0.38314768,  0.61374528,  0.66234705],
       [ 0.14920098,  0.48395971,  0.11457635,  0.90097183, -0.78736643,
         0.2107782 ,  1.00117534, -1.61602119,  1.28837441, -2.16527364]])

In [109]:
c = []

In [110]:
arr = np.array(c)

In [111]:
arr

array([], dtype=float64)

In [112]:
arr = np.zeros((0,0))

In [113]:
arr

array([], shape=(0, 0), dtype=float64)

In [114]:
arr = np.array((x:=[2,4,5,1,7,8,6,9,6,4]))

In [115]:
arr

array([2, 4, 5, 1, 7, 8, 6, 9, 6, 4])

eye - it create a numpy array having ones at diagonals.

In [116]:
arr = np.eye(3)

In [117]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [118]:
arr = np.eye(5,6)

In [119]:
arr

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [120]:
arr = np.eye(6,4)

In [121]:
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

logspace - it is used to generate a set of number whose ratio is same not difference in log scale.

In [122]:
arr = np.logspace(start=-2,stop=3,base=10,num=5)

In [123]:
arr

array([1.00000000e-02, 1.77827941e-01, 3.16227766e+00, 5.62341325e+01,
       1.00000000e+03])

In [124]:
arr = np.logspace(start=-2,stop=3,base=2,num=6)

In [125]:
arr

array([0.25, 0.5 , 1.  , 2.  , 4.  , 8.  ])

concatenate = it is used to combine two numpy arrays in different axises and can concatenate multiple numpy arrays .

In [126]:
left_arr = np.random.binomial(n=7,p=0.4,size=(2,6))
right_arr = np.random.binomial(n=10,p=0.6,size=(2,6))

In [127]:
row_wise_concat_arr = np.concatenate((left_arr,right_arr),axis=0)
col_wise_concat_arr = np.concatenate((left_arr,right_arr),axis=1)


In [128]:
row_wise_concat_arr

array([[3, 5, 1, 1, 1, 1],
       [2, 0, 4, 0, 2, 2],
       [5, 7, 8, 5, 4, 7],
       [7, 7, 7, 7, 6, 9]])

In [129]:
col_wise_concat_arr

array([[3, 5, 1, 1, 1, 1, 5, 7, 8, 5, 4, 7],
       [2, 0, 4, 0, 2, 2, 7, 7, 7, 7, 6, 9]])

delete = it deletes the rows or columns or depths of which axises are given.(in this condition)

In [130]:
col_wise_concat_arr = np.delete(col_wise_concat_arr,[1,3],axis=1)

In [131]:
col_wise_concat_arr

array([[3, 1, 1, 1, 5, 7, 8, 5, 4, 7],
       [2, 4, 2, 2, 7, 7, 7, 7, 6, 9]])

In [132]:
row_wise_concat_arr = np.delete(row_wise_concat_arr,[1,3],axis=0)

In [133]:
row_wise_concat_arr

array([[3, 5, 1, 1, 1, 1],
       [5, 7, 8, 5, 4, 7]])

Done -> Concept of boolean masking in numpy arrays . 

In [134]:
bmask = np.ones((col_wise_concat_arr.shape[1],),dtype=bool)

In [135]:
bmask

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [136]:
bmask[1]=False
bmask[5]=False

In [137]:
bmask

array([ True, False,  True,  True,  True, False,  True,  True,  True,
        True])

In [138]:
col_wise_concat_arr[:,bmask]

array([[3, 1, 1, 5, 8, 5, 4, 7],
       [2, 2, 2, 7, 7, 7, 6, 9]])

In [139]:
bmask1=np.ones((row_wise_concat_arr.shape[0],),dtype=bool)

In [140]:
bmask1

array([ True,  True])

In [141]:
bmask1[1]=False
bmask1[3]=False

IndexError: index 3 is out of bounds for axis 0 with size 2

In [ ]:
bmask1

array([ True, False,  True, False])

In [ ]:
row_wise_concat_arr[bmask1,:]

array([[1, 4, 1, 3, 3, 2],
       [4, 9, 4, 7, 7, 5]])

In [152]:
arr8=arr8.reshape(2,6)

In [153]:
arr8

array([[ 3, 12, 10, 13, 16, 21],
       [21, 17, 20, 40, 33, 37]])

In [154]:
arr8 = np.expand_dims(arr8,axis=1)

In [155]:
arr8.shape

(2, 1, 6)

In [156]:
arr8

array([[[ 3, 12, 10, 13, 16, 21]],

       [[21, 17, 20, 40, 33, 37]]])

In [157]:
arr = np.random.randint(low=0,high=20,size=(1,2,3,4,5))

In [158]:
arr

array([[[[[ 2,  8,  5,  2, 13],
          [14, 16,  9, 13, 19],
          [ 0, 16, 17,  1,  3],
          [11, 17,  2, 19, 18]],

         [[14,  7,  2,  5,  6],
          [ 0,  3, 12, 12, 14],
          [19, 11,  8,  2, 17],
          [15, 16,  1, 15, 19]],

         [[ 7,  6,  3,  7, 15],
          [ 4,  2,  3, 17,  7],
          [ 6,  0, 10,  2,  7],
          [18,  8,  4,  2, 13]]],


        [[[10,  4,  6, 14, 12],
          [17,  7,  0, 12, 18],
          [11,  2,  6, 11,  1],
          [15,  7,  2,  3, 18]],

         [[ 7, 19, 17,  2, 17],
          [16,  8, 16, 13,  4],
          [ 2,  5, 14, 19,  0],
          [ 4,  3,  5,  1,  5]],

         [[ 4, 19, 14,  7,  8],
          [16,  9,  8, 17, 14],
          [16,  5, 14,  7, 14],
          [ 5, 17,  1,  2,  6]]]]])

In [159]:
arr.shape

(1, 2, 3, 4, 5)

Inserting new axes into a NumPy array, concept of ellipsis as well as it's notation.

In [160]:
arr = arr[:,:,np.newaxis,...]

In [161]:
arr.shape

(1, 2, 1, 3, 4, 5)