In [1]:
import numpy as np 

In [2]:
l = [1,2,3,6,5,4,8,7,9]
arr = np.array(l)
print(arr)

[1 2 3 6 5 4 8 7 9]


In [3]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [4]:
l2 = [[[1,2,3,],[4,5,6,],[7,8,9],[10,11,12]]]

In [5]:
l2

[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]]

In [6]:
np.shape(l2)

(1, 4, 3)

In [7]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [8]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [9]:
arr.shape

(9,)

In [10]:
l2 = np.reshape(l2,(3,2,2))

In [11]:
np.shape(l2)

(3, 2, 2)

In [12]:
print(l2)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [13]:
l2 [0,1,0]

np.int64(3)

In [14]:
l2 [0,0,0]

np.int64(1)

In [15]:
l2 [2,1,:]

array([11, 12])

In [16]:
l5 = [1,2,3,4,5,6,7,8,9,10]

In [17]:
l5

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [18]:
l5 * 2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [19]:
l5 = np.array(l5)

In [20]:
l5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
l5.shape

(10,)

In [22]:
l5 = l5.reshape(5,2)

In [23]:
l5

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [24]:
l6 = [1,2,3,4,5,6,7,8,9,10]

In [25]:
arr=np.array(l6)

In [26]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr* 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [28]:
arr + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [29]:
arr - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [30]:
arr.shape


(10,)

In [31]:
arr = arr.reshape(2,5)

In [32]:
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [33]:
l7 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [34]:
l7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [35]:
l7.shape

(12,)

In [36]:
l8 = np.array([1,8,4,5,6,9,7,1,2,20,11,13])

In [37]:
l8

array([ 1,  8,  4,  5,  6,  9,  7,  1,  2, 20, 11, 13])

In [38]:
l8.shape

(12,)

In [39]:
l8 = l8.reshape(1,12)

In [40]:
l8.shape

(1, 12)

In [41]:
l9 = l8 + l7

In [42]:
l9 

array([[ 2, 10,  7,  9, 11, 15, 14,  9, 11, 30, 22, 25]])

In [43]:
l9.shape

(1, 12)

In [44]:
l10 = np.array([1,5,8,7,4,6,9,2,3,6,5,4,7,8])

In [45]:
l10

array([1, 5, 8, 7, 4, 6, 9, 2, 3, 6, 5, 4, 7, 8])

In [46]:
l10.shape

(14,)

In [47]:
l10 = l10.reshape(14,1)

In [48]:
l11 = l10 + l7

In [49]:
l11

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [50]:
l12 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24])

In [51]:
l12 = l12.reshape(2,12)

In [52]:
l13 = l12 + l7

In [53]:
l13.shape

(2, 12)

In [54]:
l12 = l12.reshape(2,12)

In [55]:
l13 = l7 + l12

to add two matrix(array) we have to make their y-axis or columns of same value.

In [56]:
l13

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24],
       [14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36]])

In [57]:
l7.shape

(12,)

In [58]:
l12.shape

(2, 12)

In [59]:
l9.shape

(1, 12)

In [60]:
arr1=l9+l12

In [61]:
arr1

array([[ 3, 12, 10, 13, 16, 21, 21, 17, 20, 40, 33, 37],
       [15, 24, 22, 25, 28, 33, 33, 29, 32, 52, 45, 49]])

In [62]:
arr3=l9.reshape(1,12)

In [63]:
arr3

array([[ 2, 10,  7,  9, 11, 15, 14,  9, 11, 30, 22, 25]])

In [64]:
arr3.shape


(1, 12)

In [65]:
arr2 = l9+l7

In [66]:
arr2

array([[ 3, 12, 10, 13, 16, 21, 21, 17, 20, 40, 33, 37]])

In [67]:
l7.shape

(12,)

In [68]:
arr4=l7+l9

In [69]:
arr4

array([[ 3, 12, 10, 13, 16, 21, 21, 17, 20, 40, 33, 37]])

In [70]:
arr5 = arr4+arr3

In [71]:
arr5

array([[ 5, 22, 17, 22, 27, 36, 35, 26, 31, 70, 55, 62]])

In [72]:
arr6=l9.reshape(2,6)

In [73]:
arr7=l7.reshape(2,6)

In [74]:
arr8=arr6+arr7

In [75]:
arr8

array([[ 3, 12, 10, 13, 16, 21],
       [21, 17, 20, 40, 33, 37]])

zeros = it is used to make an array of values = 0

In [76]:
arr9 = np.zeros((2,10))

In [77]:
arr9

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [78]:
arr9=np.zeros((5,10),dtype=int)


In [79]:
arr9

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

ones = it is used to generate an array of ony unit digits .

In [80]:
arr = np.ones((9,15))

In [81]:
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

empty = it is used to get an array of randomly generated values or garbage values .

In [82]:
arr = np.empty((4,6))

In [83]:
arr

array([[3.5458676e-315, 0.0000000e+000, 3.4584595e-323, 4.4465908e-323,
        5.4347221e-323, 7.4109847e-323],
       [6.9169190e-323, 4.4465908e-323, 5.4347221e-323, 1.4821969e-322,
        1.0869444e-322, 1.2351641e-322],
       [9.8813129e-324, 4.9406565e-323, 3.4584595e-323, 4.4465908e-323,
        5.4347221e-323, 7.4109847e-323],
       [6.9169190e-323, 4.4465908e-323, 5.4347221e-323, 1.4821969e-322,
        1.0869444e-322, 1.2351641e-322]])

In [84]:
arr = np.empty((4,6),dtype=int)

In [85]:
arr 

array([[717691592,         0,         7,         9,        11,        15],
       [       14,         9,        11,        30,        22,        25],
       [        2,        10,         7,         9,        11,        15],
       [       14,         9,        11,        30,        22,        25]])

arange = it is used to get an array of desired staring point & ending point with how much differnce we want in the two values .

In [86]:
arr = np.arange(0,20,2.5,dtype=np.float64)

In [87]:
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5])

linspace = it is used to make an array of desired staring point & ending point with how much values we want then the funtion will generate the gap itself according to the values 

In [88]:
arr = np.linspace(0,10,20)

In [89]:
arr

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [90]:
arr = np.random.binomial(n=6,p=0.6,size=(2,5))

In [91]:
arr

array([[4, 3, 4, 2, 3],
       [2, 3, 5, 3, 4]])

In [92]:
arr = np.random.binomial(n=1,p=0.5,size=(2,5))

In [93]:
arr

array([[0, 0, 1, 1, 1],
       [0, 0, 1, 1, 0]])

In [94]:
arr = np.random.multivariate_normal(mean=[1,1,1,1],cov=[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]],size=10)

In [95]:
arr

array([[ 0.04085884,  2.02799605,  0.26859767,  2.5583718 ],
       [ 0.59427308,  1.34040416,  1.23331478, -0.06969184],
       [ 0.81473897,  1.47311643,  0.18439131,  1.39365111],
       [ 3.50053708, -0.39380891,  0.51648701,  0.93185806],
       [-0.44719192,  2.10090926,  2.27601901,  1.37477615],
       [ 0.27359608,  0.55442305,  1.88435355,  2.53747133],
       [ 1.42998178,  0.7556492 , -1.02265354,  2.00858143],
       [ 0.3702049 ,  2.29630082,  1.19761921,  1.93955831],
       [ 2.72961328,  0.84375074,  1.40390503, -0.41271116],
       [ 1.52733175,  0.84042183, -0.01873739,  1.19102965]])

In [96]:
arr = np.random.multivariate_normal(mean=[1,2,3,4],cov=[[1,0,0,0],[0,2,0,0],[0,0,3,0],[0,0,0,4]],size=10)

In [97]:
arr

array([[ 6.82833628e-01,  2.30291225e+00,  9.66856147e-01,
        -7.70753004e-01],
       [ 1.58592081e+00,  3.10251346e+00,  1.20322596e+00,
         4.28035613e+00],
       [-4.02890750e-03,  6.15315915e-01,  1.49484929e+00,
         4.38482273e+00],
       [ 1.35791626e+00,  4.73767379e-01,  3.71518028e+00,
         4.11660951e+00],
       [ 3.56228031e+00,  3.13013129e+00,  8.83021304e-01,
         2.31125934e+00],
       [ 5.58035756e-01,  3.39232944e+00,  2.80259472e+00,
         3.64996695e+00],
       [-1.72443605e-01,  2.32934211e+00,  1.58039964e+00,
         2.27104887e+00],
       [ 1.82245694e+00,  2.49033143e+00,  1.42668750e+00,
         3.23675137e+00],
       [ 1.87271390e+00,  2.47346662e+00,  3.77655893e+00,
         5.33968929e+00],
       [-1.29735721e-01,  2.19792283e+00,  8.18961877e-01,
         6.50033860e+00]])

In [98]:
arr = np.random.normal(loc=5,scale=1,size=(2,10))

In [99]:
arr

array([[6.43950509, 3.39429114, 5.47492387, 5.29852684, 5.83479495,
        5.31499131, 5.82468754, 3.99889084, 5.20453546, 4.35850719],
       [6.42377435, 5.32185417, 3.87591143, 4.92030437, 4.00271326,
        5.00927527, 6.15292758, 5.13506038, 4.17491008, 5.1606709 ]])

In [100]:
arr_mean=np.mean(arr)

In [101]:
arr_mean

np.float64(5.066052802181204)

In [102]:
arr = np.random.rand(10,10)

In [103]:
arr

array([[0.26284893, 0.00665936, 0.56350077, 0.49009319, 0.7195709 ,
        0.25975955, 0.33656392, 0.85873562, 0.00543412, 0.91068574],
       [0.38763296, 0.0386369 , 0.4018721 , 0.24435905, 0.59170046,
        0.23593015, 0.05166654, 0.21141237, 0.47854729, 0.50740473],
       [0.51372695, 0.06354799, 0.57595871, 0.84085519, 0.72029857,
        0.14780303, 0.73791743, 0.88470987, 0.0194205 , 0.22104738],
       [0.31188317, 0.54599342, 0.1453972 , 0.19225866, 0.48227062,
        0.65604137, 0.54714355, 0.39794099, 0.86128033, 0.78473913],
       [0.02954395, 0.93194365, 0.01869932, 0.6938593 , 0.04922129,
        0.8023999 , 0.98670661, 0.80864224, 0.40006825, 0.8267273 ],
       [0.63700558, 0.63066886, 0.77655121, 0.42068164, 0.4080088 ,
        0.34539587, 0.0975793 , 0.35496511, 0.76247403, 0.51681719],
       [0.5395387 , 0.90438778, 0.34666316, 0.98495575, 0.47955056,
        0.76855199, 0.05362228, 0.9574856 , 0.14599737, 0.3411617 ],
       [0.60641643, 0.48310176, 0.3147390

In [104]:
arr = np.random.randint(low=10,high=25,size= (2,20))

In [105]:
arr

array([[22, 24, 16, 22, 12, 11, 11, 14, 24, 12, 19, 20, 11, 13, 10, 21,
        14, 11, 24, 21],
       [18, 17, 21, 11, 22, 20, 19, 14, 15, 22, 19, 12, 21, 21, 15, 14,
        11, 12, 10, 14]])

In [106]:
arr = np.random.randn(5,10)

In [107]:
arr

array([[ 5.57976644e-01, -7.24762844e-01, -8.24548157e-01,
         7.11539820e-01,  9.03646445e-01,  2.27939637e-01,
         4.52140736e-01, -1.02349184e+00,  3.72994016e-01,
        -9.93918067e-01],
       [-1.78143244e+00,  1.19458901e+00,  3.47237928e-04,
         3.46586442e-01, -1.12616384e+00,  5.05798031e-01,
         3.68338037e-01, -1.86627615e+00,  2.52886840e+00,
        -9.07352552e-01],
       [-1.11807741e+00,  7.41564275e-01,  1.20529156e+00,
        -6.95402945e-01, -3.48492485e-01,  1.06901126e+00,
         1.12882223e+00, -2.06728826e+00,  5.40567324e-01,
         1.10499754e+00],
       [-9.95928662e-01,  3.15490253e-01, -7.81588185e-01,
        -8.01973469e-02, -9.16098925e-01,  5.05781390e-01,
         1.89161204e-01, -1.78559789e-01,  9.95403358e-01,
         5.48791924e-01],
       [ 6.12144978e-01, -1.45883888e+00,  2.98188289e-01,
         8.49500195e-01,  5.89317985e-01, -1.04281380e+00,
        -9.93765438e-01,  1.99838430e+00,  3.18289371e-01,
         2.

In [108]:
c = []

In [109]:
arr = np.array(c)

In [110]:
arr

array([], dtype=float64)

In [111]:
arr = np.zeros((0,0))

In [112]:
arr

array([], shape=(0, 0), dtype=float64)

In [113]:
arr = np.array((x:=[2,4,5,1,7,8,6,9,6,4]))

In [114]:
arr

array([2, 4, 5, 1, 7, 8, 6, 9, 6, 4])

eye - it create a numpy array having ones at diagonals.

In [115]:
arr = np.eye(3)

In [116]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [117]:
arr = np.eye(5,6)

In [118]:
arr

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [119]:
arr = np.eye(6,4)

In [120]:
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

logspace - it is used to generate a set of number whose ratio is same not difference in log scale.

In [121]:
arr = np.logspace(start=-2,stop=3,base=10,num=5)

In [122]:
arr

array([1.00000000e-02, 1.77827941e-01, 3.16227766e+00, 5.62341325e+01,
       1.00000000e+03])

In [123]:
arr = np.logspace(start=-2,stop=3,base=2,num=6)

In [124]:
arr

array([0.25, 0.5 , 1.  , 2.  , 4.  , 8.  ])

concatenate = it is used to combine two numpy arrays in different axises and can concatenate multiple numpy arrays .

In [125]:
left_arr = np.random.binomial(n=7,p=0.4,size=(2,6))
right_arr = np.random.binomial(n=10,p=0.6,size=(2,6))

In [160]:
row_wise_concat_arr = np.concatenate((left_arr,right_arr),axis=0)
col_wise_concat_arr = np.concatenate((left_arr,right_arr),axis=1)


In [161]:
row_wise_concat_arr

array([[1, 4, 1, 3, 3, 2],
       [4, 1, 3, 3, 3, 2],
       [4, 9, 4, 7, 7, 5],
       [3, 4, 3, 6, 5, 7]])

In [128]:
col_wise_concat_arr

array([[1, 4, 1, 3, 3, 2, 4, 9, 4, 7, 7, 5],
       [4, 1, 3, 3, 3, 2, 3, 4, 3, 6, 5, 7]])

delete = it deletes the rows or columns or depths of which axises are given.(in this condition)

In [129]:
col_wise_concat_arr = np.delete(col_wise_concat_arr,[1,3],axis=1)

In [130]:
col_wise_concat_arr

array([[1, 1, 3, 2, 4, 9, 4, 7, 7, 5],
       [4, 3, 3, 2, 3, 4, 3, 6, 5, 7]])

In [131]:
row_wise_concat_arr = np.delete(row_wise_concat_arr,[1,3],axis=0)

In [132]:
row_wise_concat_arr

array([[1, 4, 1, 3, 3, 2],
       [4, 9, 4, 7, 7, 5]])

Done -> Concept of boolean masking in numpy arrays .

In [134]:
bmask = np.ones((col_wise_concat_arr.shape[1],),dtype=bool)

In [135]:
bmask

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [136]:
bmask[1]=False
bmask[5]=False

In [137]:
bmask

array([ True, False,  True,  True,  True, False,  True,  True,  True,
        True])

In [138]:
col_wise_concat_arr[:,bmask]

array([[1, 3, 2, 4, 4, 7, 7, 5],
       [4, 3, 2, 3, 3, 6, 5, 7]])

In [151]:
bmask1=np.ones((row_wise_concat_arr.shape[0],),dtype=bool)

In [152]:
bmask1

array([ True,  True,  True,  True])

In [153]:
bmask1[1]=False
bmask1[3]=False

In [158]:
bmask1

array([ True, False,  True, False])

In [162]:
row_wise_concat_arr[bmask1,:]

array([[1, 4, 1, 3, 3, 2],
       [4, 9, 4, 7, 7, 5]])