In [282]:
import numpy as np 

In [283]:
l = [1,2,3,6,5,4,8,7,9]
arr = np.array(l)
print(arr)

[1 2 3 6 5 4 8 7 9]


In [284]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [285]:
l2 = [[[1,2,3,],[4,5,6,],[7,8,9],[10,11,12]]]

In [286]:
l2

[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]]

In [287]:
np.shape(l2)

(1, 4, 3)

In [288]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [289]:
arr

array([1, 2, 3, 6, 5, 4, 8, 7, 9])

In [290]:
arr.shape

(9,)

In [291]:
l2 = np.reshape(l2,(3,2,2))

In [292]:
np.shape(l2)

(3, 2, 2)

In [293]:
print(l2)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [294]:
l2 [0,1,0]

np.int64(3)

In [295]:
l2 [0,0,0]

np.int64(1)

In [296]:
l2 [2,1,:]

array([11, 12])

In [297]:
l5 = [1,2,3,4,5,6,7,8,9,10]

In [298]:
l5

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [299]:
l5 * 2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [300]:
l5 = np.array(l5)

In [301]:
l5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [302]:
l5.shape

(10,)

In [303]:
l5 = l5.reshape(5,2)

In [304]:
l5

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [305]:
l6 = [1,2,3,4,5,6,7,8,9,10]

In [306]:
arr=np.array(l6)

In [307]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [308]:
arr* 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [309]:
arr + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [310]:
arr - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [311]:
arr.shape


(10,)

In [312]:
arr = arr.reshape(2,5)

In [313]:
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [314]:
l7 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [315]:
l7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [316]:
l7.shape

(12,)

In [317]:
l8 = np.array([1,8,4,5,6,9,7,1,2,20,11,13])

In [318]:
l8

array([ 1,  8,  4,  5,  6,  9,  7,  1,  2, 20, 11, 13])

In [319]:
l8.shape

(12,)

In [320]:
l8 = l8.reshape(1,12)

In [321]:
l8.shape

(1, 12)

In [322]:
l9 = l8 + l7

In [323]:
l9 

array([[ 2, 10,  7,  9, 11, 15, 14,  9, 11, 30, 22, 25]])

In [324]:
l9.shape

(1, 12)

In [325]:
l10 = np.array([1,5,8,7,4,6,9,2,3,6,5,4,7,8])

In [326]:
l10

array([1, 5, 8, 7, 4, 6, 9, 2, 3, 6, 5, 4, 7, 8])

In [327]:
l10.shape

(14,)

In [328]:
l10 = l10.reshape(14,1)

In [329]:
l11 = l10 + l7

In [330]:
l11

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [331]:
l12 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24])

In [332]:
l12 = l12.reshape(2,12)

In [333]:
l13 = l12 + l7

In [334]:
l13.shape

(2, 12)

In [335]:
l12 = l12.reshape(2,12)

In [336]:
l13 = l7 + l12

to add two matrix(array) we have to make their y-axis or columns of same value.

In [337]:
l13

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24],
       [14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36]])

In [338]:
l7.shape

(12,)

In [339]:
l12.shape

(2, 12)

In [340]:
l9.shape

(1, 12)

In [341]:
arr1=l9+l12

In [342]:
arr1

array([[ 3, 12, 10, 13, 16, 21, 21, 17, 20, 40, 33, 37],
       [15, 24, 22, 25, 28, 33, 33, 29, 32, 52, 45, 49]])

In [343]:
arr3=l9.reshape(1,12)

In [344]:
arr3

array([[ 2, 10,  7,  9, 11, 15, 14,  9, 11, 30, 22, 25]])

In [345]:
arr3.shape


(1, 12)

In [346]:
arr2 = l9+l7

In [347]:
arr2

array([[ 3, 12, 10, 13, 16, 21, 21, 17, 20, 40, 33, 37]])

In [348]:
l7.shape

(12,)

In [349]:
arr4=l7+l9

In [350]:
arr4

array([[ 3, 12, 10, 13, 16, 21, 21, 17, 20, 40, 33, 37]])

In [351]:
arr5 = arr4+arr3

In [352]:
arr5

array([[ 5, 22, 17, 22, 27, 36, 35, 26, 31, 70, 55, 62]])

In [353]:
arr6=l9.reshape(2,6)    

In [354]:
arr7=l7.reshape(2,6)

In [355]:
arr8=arr6+arr7

In [356]:
arr8

array([[ 3, 12, 10, 13, 16, 21],
       [21, 17, 20, 40, 33, 37]])

zeros = it is used to make an array of values = 0

In [357]:
arr9 = np.zeros((2,10))

In [358]:
arr9

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [359]:
arr9=np.zeros((5,10),dtype=int)


In [360]:
arr9

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

ones = it is used to generate an array of ony unit digits .

In [361]:
arr = np.ones((9,15))

In [362]:
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

empty = it is used to get an array of randomly generated values or garbage values .

In [363]:
arr = np.empty((4,6))

In [364]:
arr

array([[3.41226651e-315, 0.00000000e+000, 3.45845952e-323,
        4.44659081e-323, 5.43472210e-323, 7.41098469e-323],
       [6.91691904e-323, 4.44659081e-323, 5.43472210e-323,
        1.48219694e-322, 1.08694442e-322, 1.23516411e-322],
       [9.88131292e-324, 4.94065646e-323, 3.45845952e-323,
        4.44659081e-323, 5.43472210e-323, 7.41098469e-323],
       [6.91691904e-323, 4.44659081e-323, 5.43472210e-323,
        1.48219694e-322, 1.08694442e-322, 1.23516411e-322]])

In [365]:
arr = np.empty((4,6),dtype=int)

In [366]:
arr 

array([[690650430,         0,         7,         9,        11,        15],
       [       14,         9,        11,        30,        22,        25],
       [        2,        10,         7,         9,        11,        15],
       [       14,         9,        11,        30,        22,        25]])

arange = it is used to get an array of desired staring point & ending point with how much differnce we want in the two values .

In [367]:
arr = np.arange(0,20,2.5,dtype=np.float64)

In [368]:
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5])

linspace = it is used to make an array of desired staring point & ending point with how much values we want then the funtion will generate the gap itself according to the values 

In [369]:
arr = np.linspace(0,10,20)

In [370]:
arr

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [371]:
arr = np.random.binomial(n=6,p=0.6,size=(2,5))

In [372]:
arr

array([[3, 4, 2, 3, 6],
       [3, 3, 4, 3, 3]])

In [373]:
arr = np.random.binomial(n=1,p=0.5,size=(2,5))

In [374]:
arr

array([[1, 0, 1, 0, 1],
       [0, 0, 0, 0, 1]])

In [375]:
arr = np.random.multivariate_normal(mean=[1,1,1,1],cov=[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]],size=10)

In [376]:
arr

array([[ 0.14866294,  0.02464287,  0.50390094,  1.57115619],
       [-0.63866401,  0.1908379 , -0.12852847,  1.65849887],
       [ 0.38280709,  0.4159401 ,  0.95520752,  0.41145845],
       [ 1.60051212,  0.52691369,  1.96858865,  1.84938518],
       [ 0.42513917,  1.33596078,  2.23289597,  2.36532669],
       [ 1.21098887,  2.1633827 ,  1.73931912,  1.456684  ],
       [ 0.9573995 ,  2.09811065, -0.29884006,  1.76287464],
       [ 0.76063682,  1.32087964, -0.05144735, -1.39190681],
       [ 0.46232182, -1.26124735,  3.73589214,  3.81059047],
       [ 1.66505572,  0.8961683 ,  1.06984235, -0.49096326]])

In [377]:
arr = np.random.multivariate_normal(mean=[1,2,3,4],cov=[[1,0,0,0],[0,2,0,0],[0,0,3,0],[0,0,0,4]],size=10)

In [378]:
arr

array([[-0.53789742,  1.16184096,  5.88389001,  6.47036124],
       [ 2.22115409,  3.98847609,  2.25379449,  3.80753881],
       [ 1.16593499,  0.56289758,  4.06843929,  6.38516876],
       [ 1.03492727,  1.87015083,  2.88990033,  4.0061404 ],
       [ 0.91295045,  4.31013777,  3.16615244,  2.2156363 ],
       [-0.05289387,  3.62091873,  4.85864223,  3.22426713],
       [ 2.69047679,  2.7036602 ,  3.26152832, -1.04760333],
       [-0.28340622,  1.87285396,  3.59400957,  3.07245072],
       [ 0.25586328,  0.77295125,  5.28466679,  3.60576044],
       [ 3.17127827,  0.94228242,  1.21901601,  1.11496745]])

In [379]:
arr = np.random.normal(loc=5,scale=1,size=(2,10))

In [380]:
arr

array([[8.19969489, 3.8426347 , 5.32362341, 5.27904507, 6.02007175,
        4.77851073, 3.44154424, 2.02353303, 5.69915967, 6.06119028],
       [5.20401387, 4.03903287, 6.55815203, 6.37355379, 4.33041633,
        5.46250318, 4.83051678, 4.30960458, 6.86180886, 5.36932012]])

In [381]:
arr_mean=np.mean(arr)

In [382]:
arr_mean

np.float64(5.200396509189586)

In [383]:
arr = np.random.rand(10,10)

In [384]:
arr

array([[0.21978351, 0.95037445, 0.33043834, 0.94886661, 0.7912786 ,
        0.43778741, 0.88115627, 0.15784313, 0.29190133, 0.85333346],
       [0.6271916 , 0.62953506, 0.56156561, 0.67203983, 0.66776386,
        0.46712903, 0.77952818, 0.09907942, 0.1324157 , 0.35000498],
       [0.45246993, 0.06502265, 0.81455651, 0.78459797, 0.02484497,
        0.88464824, 0.80875678, 0.6872838 , 0.52415564, 0.23914021],
       [0.66009188, 0.89991038, 0.23660976, 0.15500458, 0.11234873,
        0.86979467, 0.18316023, 0.56803896, 0.18981628, 0.99725185],
       [0.68550752, 0.15496386, 0.88467077, 0.10190239, 0.4274257 ,
        0.04127602, 0.7481601 , 0.7303438 , 0.29443467, 0.81368905],
       [0.88156426, 0.63444414, 0.97433719, 0.80470319, 0.59931479,
        0.29386937, 0.01151026, 0.60217153, 0.44917104, 0.15431239],
       [0.3798101 , 0.20142986, 0.09590532, 0.48092518, 0.30587174,
        0.73906771, 0.21804916, 0.31386501, 0.85647041, 0.16423052],
       [0.91555142, 0.8690157 , 0.5008036

In [385]:
arr = np.random.randint(low=10,high=25,size= (2,20))

In [386]:
arr

array([[22, 23, 24, 16, 16, 19, 22, 22, 11, 21, 15, 20, 23, 24, 23, 18,
        11, 11, 18, 24],
       [17, 23, 22, 16, 19, 22, 14, 22, 12, 24, 17, 13, 19, 22, 15, 24,
        21, 10, 19, 11]])

In [387]:
arr = np.random.randn(5,10)

In [388]:
arr

array([[-0.75965406, -0.06075627,  0.17658153,  2.0109514 , -1.23881906,
        -0.045079  ,  0.27099334,  1.00131579, -0.8595411 , -1.40781386],
       [-1.17851477, -1.7311759 ,  1.04190929, -0.84852339,  1.53838227,
        -0.74505216, -0.06478155,  0.09340188,  0.33380268, -0.30090695],
       [-1.05087001,  0.62153413, -0.26470838, -0.02468429, -1.45145214,
         0.47833348, -0.59831426, -0.15804824, -1.05845022,  0.2201029 ],
       [ 0.46415806, -0.9818828 , -0.29137569,  0.1903588 , -0.15067719,
        -0.87293023,  0.7557026 ,  0.17231886, -0.57159796,  0.62169576],
       [-0.95204688, -1.04381132, -1.07817691,  1.12485877, -2.43791794,
        -0.69460038,  0.16876106,  0.35573139, -1.22046557, -0.32510721]])

In [389]:
c = []

In [390]:
arr = np.array(c)

In [391]:
arr

array([], dtype=float64)

In [392]:
arr = np.zeros((0,0))

In [393]:
arr

array([], shape=(0, 0), dtype=float64)

In [394]:
arr = np.array((x:=[2,4,5,1,7,8,6,9,6,4]))

In [395]:
arr

array([2, 4, 5, 1, 7, 8, 6, 9, 6, 4])

eye - it create a numpy array having ones at diagonals.

In [396]:
arr = np.eye(3)

In [397]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [398]:
arr = np.eye(5,6)

In [399]:
arr

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [400]:
arr = np.eye(6,4)

In [401]:
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

logspace - it is used to generate a set of number whose ratio is same not difference in log scale.

In [402]:
arr = np.logspace(start=-2,stop=3,base=10,num=5)

In [403]:
arr

array([1.00000000e-02, 1.77827941e-01, 3.16227766e+00, 5.62341325e+01,
       1.00000000e+03])

In [404]:
arr = np.logspace(start=-2,stop=3,base=2,num=6)

In [405]:
arr

array([0.25, 0.5 , 1.  , 2.  , 4.  , 8.  ])

concatenate = it is used to combine two numpy arrays in different axises and can concatenate multiple numpy arrays .

In [406]:
left_arr = np.random.binomial(n=7,p=0.4,size=(2,6))
right_arr = np.random.binomial(n=10,p=0.6,size=(2,6))

In [407]:
row_wise_concat_arr = np.concatenate((left_arr,right_arr),axis=0)
col_wise_concat_arr = np.concatenate((left_arr,right_arr),axis=1)


In [408]:
row_wise_concat_arr

array([[2, 2, 3, 0, 3, 4],
       [2, 5, 0, 1, 4, 3],
       [6, 8, 6, 5, 6, 8],
       [6, 6, 6, 5, 9, 5]])

In [409]:
col_wise_concat_arr

array([[2, 2, 3, 0, 3, 4, 6, 8, 6, 5, 6, 8],
       [2, 5, 0, 1, 4, 3, 6, 6, 6, 5, 9, 5]])

delete = it deletes the rows or columns or depths of which axises are given.(in this condition)

In [410]:
col_wise_concat_arr = np.delete(col_wise_concat_arr,[1,3],axis=1)

In [411]:
col_wise_concat_arr

array([[2, 3, 3, 4, 6, 8, 6, 5, 6, 8],
       [2, 0, 4, 3, 6, 6, 6, 5, 9, 5]])

In [412]:
row_wise_concat_arr = np.delete(row_wise_concat_arr,[1,3],axis=0)

In [413]:
row_wise_concat_arr

array([[2, 2, 3, 0, 3, 4],
       [6, 8, 6, 5, 6, 8]])

Done -> Concept of boolean masking in numpy arrays . 

In [414]:
bmask = np.ones((col_wise_concat_arr.shape[1],),dtype=bool)

In [415]:
bmask

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [416]:
bmask[1]=False
bmask[5]=False

In [417]:
bmask

array([ True, False,  True,  True,  True, False,  True,  True,  True,
        True])

In [418]:
col_wise_concat_arr[:,bmask]

array([[2, 3, 4, 6, 6, 5, 6, 8],
       [2, 4, 3, 6, 6, 5, 9, 5]])

In [419]:
bmask1=np.ones((row_wise_concat_arr.shape[0],),dtype=bool)

In [420]:
bmask1

array([ True,  True])

In [421]:
bmask1[1]=False
bmask1[3]=False

IndexError: index 3 is out of bounds for axis 0 with size 2

In [ ]:
bmask1

array([ True, False,  True, False])

In [ ]:
row_wise_concat_arr[bmask1,:]

array([[1, 4, 1, 3, 3, 2],
       [4, 9, 4, 7, 7, 5]])

In [ ]:
arr8=arr8.reshape(2,6)

In [ ]:
arr8

array([[ 3, 12, 10, 13, 16, 21],
       [21, 17, 20, 40, 33, 37]])

In [ ]:
arr8 = np.expand_dims(arr8,axis=1)

In [ ]:
arr8.shape

(2, 1, 6)

In [ ]:
arr8

array([[[ 3, 12, 10, 13, 16, 21]],

       [[21, 17, 20, 40, 33, 37]]])

In [ ]:
arr = np.random.randint(low=0,high=20,size=(1,2,3,4,5))

In [ ]:
arr

array([[[[[ 2,  8,  5,  2, 13],
          [14, 16,  9, 13, 19],
          [ 0, 16, 17,  1,  3],
          [11, 17,  2, 19, 18]],

         [[14,  7,  2,  5,  6],
          [ 0,  3, 12, 12, 14],
          [19, 11,  8,  2, 17],
          [15, 16,  1, 15, 19]],

         [[ 7,  6,  3,  7, 15],
          [ 4,  2,  3, 17,  7],
          [ 6,  0, 10,  2,  7],
          [18,  8,  4,  2, 13]]],


        [[[10,  4,  6, 14, 12],
          [17,  7,  0, 12, 18],
          [11,  2,  6, 11,  1],
          [15,  7,  2,  3, 18]],

         [[ 7, 19, 17,  2, 17],
          [16,  8, 16, 13,  4],
          [ 2,  5, 14, 19,  0],
          [ 4,  3,  5,  1,  5]],

         [[ 4, 19, 14,  7,  8],
          [16,  9,  8, 17, 14],
          [16,  5, 14,  7, 14],
          [ 5, 17,  1,  2,  6]]]]])

In [ ]:
arr.shape

(1, 2, 3, 4, 5)

Inserting new axes into a NumPy array, concept of ellipsis as well as it's notation.

In [ ]:
arr = arr[:,:,np.newaxis,...]

In [ ]:
arr.shape

(1, 2, 1, 3, 4, 5)

squeeze = it is used to squeeze the size of an array by removing all 1 .

In [ ]:
squeezed_arr=np.squeeze(arr)

In [ ]:
squeezed_arr.shape

(2, 3, 4, 5)

ravel = it is used to make a single dimnesion array with all the elements .

In [ ]:
flattened_arr = np.ravel(squeezed_arr)

In [ ]:
flattened_arr.shape

(120,)

reshape = it is used to reshape an array in different dimensions but the no. of elements should be same.

In [ ]:
reshaped_arr = np.reshape(squeezed_arr,newshape=(3,5,4,1,2))

/tmp/ipykernel_2365/1100543301.py:1: DeprecationWarning: `newshape` keyword argument is deprecated, use `shape=...` or pass shape positionally instead. (deprecated in NumPy 2.1)
  reshaped_arr = np.reshape(squeezed_arr,newshape=(3,5,4,1,2))


In [ ]:
reshaped_arr.shape

(3, 5, 4, 1, 2)

In [ ]:
reshaped_arr = np.reshape(squeezed_arr,newshape=(15,1,8))

/tmp/ipykernel_2365/1744322687.py:1: DeprecationWarning: `newshape` keyword argument is deprecated, use `shape=...` or pass shape positionally instead. (deprecated in NumPy 2.1)
  reshaped_arr = np.reshape(squeezed_arr,newshape=(15,1,8))


In [ ]:
reshaped_arr.shape

(15, 1, 8)

In [ ]:
reshaped_arr = np.reshape(squeezed_arr,newshape=(120,))

/tmp/ipykernel_2365/4254991431.py:1: DeprecationWarning: `newshape` keyword argument is deprecated, use `shape=...` or pass shape positionally instead. (deprecated in NumPy 2.1)
  reshaped_arr = np.reshape(squeezed_arr,newshape=(120,))


In [ ]:
reshaped_arr.shape

(120,)

In [ ]:
arr = np.random.randint(low=0,hogh=20,size=10)

In [ ]:
arr

array([0.25, 0.5 , 1.  , 2.  , 4.  , 8.  ])

padding = it is used to add values on the basis of applications. now I have used padding for 1d-array.

In [422]:
padded_arr=np.pad(arr,pad_width=(0,5),mode='constant',constant_values=0)

In [423]:
padded_arr

array([0.25, 0.5 , 1.  , 2.  , 4.  , 8.  , 0.  , 0.  , 0.  , 0.  , 0.  ])

In [424]:
padded_arr1 = np.pad(arr,pad_width=(5,0),mode='edge')

In [425]:
padded_arr1

array([0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.5 , 1.  , 2.  , 4.  , 8.  ])

In [426]:
padded_arr = np.pad(arr,pad_width=(2,3),mode='linear_ramp',end_values=(0.05,12))

In [427]:
padded_arr

array([ 0.05      ,  0.15      ,  0.25      ,  0.5       ,  1.        ,
        2.        ,  4.        ,  8.        ,  9.33333333, 10.66666667,
       12.        ])

In [428]:
padded_arr = np.pad(arr,pad_width=(3,2),mode='mean')

In [429]:
padded_arr

array([2.625, 2.625, 2.625, 0.25 , 0.5  , 1.   , 2.   , 4.   , 8.   ,
       2.625, 2.625])

In [431]:
padded_arr = np.pad(arr,pad_width=(2,3),mode='reflect')

In [432]:
padded_arr

array([1.  , 0.5 , 0.25, 0.5 , 1.  , 2.  , 4.  , 8.  , 4.  , 2.  , 1.  ])